-- ==============================================================
-- Script: 12_migration_inventory_db_corrispondenze.sql
-- Purpose: Inventory "db corrispondenze" — semaphore, staging, snapshot,
--          lookup merge, audit, sync + snapshot purge.
-- Aligns with Liquibase-style single-file change set (change 12).
--
-- Prerequisites:
--   - application_staging.etl_monitoring, dblink, application_data.log_error_write_cfg
--
-- FDW inventory (expected ~3 new remote tables, schema TBD): add in a later migration when definitions exist.
--
-- Not in this file: application_staging.etl_run_inventory (KPI) — future change set.
-- ==============================================================

-- ----------------------------------------------------------------
-- 1) Semaphore: one row per SharePoint / Java ingestion run
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS application_staging.inventory_ingestion_run CASCADE;
CREATE TABLE IF NOT EXISTS application_staging.inventory_ingestion_run (
    run_id              uuid PRIMARY KEY,
    plant_id            bigint NOT NULL,
    overall_status      varchar(40) NOT NULL DEFAULT 'OPEN',
    created_ts_utc      timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    updated_ts_utc      timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    source_file_hint    varchar(500) NULL,
    notes               text NULL,
    CONSTRAINT chk_inventory_ingestion_run_status CHECK (
        overall_status IN (
            'OPEN', 'LOADING', 'READY_FOR_SYNC', 'SYNCING', 'SYNC_DONE', 'FAILED', 'SYNC_FAILED'
        )
    )
);

CREATE INDEX IF NOT EXISTS idx_inventory_ingestion_run_plant_status
    ON application_staging.inventory_ingestion_run (plant_id, overall_status);

COMMENT ON TABLE application_staging.inventory_ingestion_run IS
    'Java/SharePoint ingestion gate: overall_status transitions; READY_FOR_SYNC when all sheets SUCCESS before DB sync.';

-- ----------------------------------------------------------------
-- 2) Per-sheet status for all-or-nothing gate (typically 4 sheets)
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS application_staging.inventory_ingestion_run_sheet;
CREATE TABLE IF NOT EXISTS application_staging.inventory_ingestion_run_sheet (
    run_id          uuid NOT NULL REFERENCES application_staging.inventory_ingestion_run (run_id) ON DELETE CASCADE,
    sheet_name      varchar(200) NOT NULL,
    sheet_status    varchar(20) NOT NULL DEFAULT 'PENDING',
    row_count       integer NOT NULL DEFAULT 0,
    last_error      text NULL,
    updated_ts_utc  timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    CONSTRAINT pk_inventory_ingestion_run_sheet PRIMARY KEY (run_id, sheet_name),
    CONSTRAINT chk_inventory_ingestion_run_sheet_status CHECK (
        sheet_status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')
    )
);

CREATE INDEX IF NOT EXISTS idx_inventory_ingestion_run_sheet_run
    ON application_staging.inventory_ingestion_run_sheet (run_id);

COMMENT ON TABLE application_staging.inventory_ingestion_run_sheet IS
    'Per-sheet ingestion outcome; ETL sync requires all expected sheets SUCCESS and run READY_FOR_SYNC.';

-- ----------------------------------------------------------------
-- 3) Staging — full workbook rows (union of sheets), keyed by run_id
--    Column set matches SharePoint workbook (db corrispondenze.xlsx).
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS application_staging.db_corrispondenze_inventory;
CREATE TABLE IF NOT EXISTS application_staging.db_corrispondenze_inventory (
    staging_row_id      bigint GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1
    ) NOT NULL,
    run_id              uuid NOT NULL,
    plant_id            bigint NOT NULL,
    sheet               varchar(200) NOT NULL,
    distinta            varchar(500) NOT NULL,
    descrizione         text NULL,
    premontato          varchar(500) NULL,
    descrizione1        text NULL,
    linea               varchar(500) NULL,
    ripetizioni         varchar(100) NULL,
    magazzino           varchar(255) NULL,
    valid_from_day_id   numeric(8) NULL,
    valid_to_day_id     numeric(8) NULL,
    CONSTRAINT pk_db_corrispondenze_inventory PRIMARY KEY (staging_row_id)
);

CREATE INDEX IF NOT EXISTS idx_db_corrispondenze_inventory_run_plant
    ON application_staging.db_corrispondenze_inventory (run_id, plant_id);
CREATE INDEX IF NOT EXISTS idx_db_corrispondenze_inventory_run_sheet
    ON application_staging.db_corrispondenze_inventory (run_id, sheet);

COMMENT ON TABLE application_staging.db_corrispondenze_inventory IS
    'Staging: full daily workbook load per run_id (all sheets). Java inserts; sync moves to snapshot and merges into LK.';

-- ----------------------------------------------------------------
-- 4) Snapshot — archival copy 1:1 after successful LK sync
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS application_staging.db_corrispondenze_inventory_snapshot;
CREATE TABLE IF NOT EXISTS application_staging.db_corrispondenze_inventory_snapshot (
    snapshot_row_id     bigint GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1
    ) NOT NULL,
    run_id              uuid NOT NULL,
    plant_id            bigint NOT NULL,
    snapshot_day_id     numeric(8) NOT NULL,
    loaded_ts_utc       timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    sheet               varchar(200) NOT NULL,
    distinta            varchar(500) NOT NULL,
    descrizione         text NULL,
    premontato          varchar(500) NULL,
    descrizione1        text NULL,
    linea               varchar(500) NULL,
    ripetizioni         varchar(100) NULL,
    magazzino           varchar(255) NULL,
    valid_from_day_id   numeric(8) NULL,
    valid_to_day_id     numeric(8) NULL,
    CONSTRAINT pk_db_corrispondenze_inventory_snapshot PRIMARY KEY (snapshot_row_id)
);

CREATE INDEX IF NOT EXISTS idx_db_corr_snap_run_plant
    ON application_staging.db_corrispondenze_inventory_snapshot (run_id, plant_id);
CREATE INDEX IF NOT EXISTS idx_db_corr_snap_purge
    ON application_staging.db_corrispondenze_inventory_snapshot (loaded_ts_utc);
CREATE INDEX IF NOT EXISTS idx_db_corr_snap_plant_day
    ON application_staging.db_corrispondenze_inventory_snapshot (plant_id, snapshot_day_id);

COMMENT ON TABLE application_staging.db_corrispondenze_inventory_snapshot IS
    'Historical copies of workbook rows after successful LK sync; retention via purge_db_corrispondenze_inventory_snapshot_older_than.';

-- ----------------------------------------------------------------
-- 5) Lookup (application_data) — merged state; soft-delete for removals
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS application_data.lk_db_corrispondenze_inventory CASCADE;
CREATE TABLE IF NOT EXISTS application_data.lk_db_corrispondenze_inventory (
    inventory_corr_id   bigint GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1
    ) NOT NULL,
    plant_id            bigint NOT NULL,
    distinta            varchar(500) NOT NULL,
    descrizione         text NULL,
    premontato          varchar(500) NULL,
    descrizione1        text NULL,
    linea               varchar(500) NULL,
    ripetizioni         varchar(100) NULL,
    magazzino           varchar(255) NULL,
    sheet_last          varchar(200) NULL,
    valid_from_day_id   numeric(8) NULL,
    valid_to_day_id     numeric(8) NULL,
    row_hash            varchar(64) NULL,
    is_active           boolean NOT NULL DEFAULT true,
    is_deleted          boolean NOT NULL DEFAULT false,
    creation_ts         timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    creator_user        varchar NOT NULL,
    last_modified       timestamp NULL DEFAULT timezone('UTC', clock_timestamp()),
    last_user           varchar NOT NULL,
    CONSTRAINT pk_lk_db_corrispondenze_inventory PRIMARY KEY (inventory_corr_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_lk_db_corr_plant_distinta_active
    ON application_data.lk_db_corrispondenze_inventory (plant_id, distinta)
    WHERE is_deleted = false;

CREATE INDEX IF NOT EXISTS idx_lk_db_corr_plant_deleted
    ON application_data.lk_db_corrispondenze_inventory (plant_id, is_deleted);

COMMENT ON TABLE application_data.lk_db_corrispondenze_inventory IS
    'Lookup from SharePoint db corrispondenze: business key (plant_id, distinta); soft-delete when distinta missing from staging run.';

-- ----------------------------------------------------------------
-- 6) Audit mirror + trigger (standalone; no dependency on script 5/6 re-run)
-- ----------------------------------------------------------------
DROP TABLE IF EXISTS application_audit.au_lk_db_corrispondenze_inventory;
CREATE TABLE application_audit.au_lk_db_corrispondenze_inventory AS
SELECT *,
       NULL::varchar(1) AS change_type,
       NULL::timestamp AS au_operation_ts
FROM application_data.lk_db_corrispondenze_inventory
WHERE false;

COMMENT ON TABLE application_audit.au_lk_db_corrispondenze_inventory IS
    'Audit trail for application_data.lk_db_corrispondenze_inventory (I/U/D).';

CREATE OR REPLACE FUNCTION application_data.fn_audit_lk_db_corrispondenze_inventory()
RETURNS trigger
LANGUAGE plpgsql
AS $f$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO application_audit.au_lk_db_corrispondenze_inventory
        SELECT NEW.*, 'I', timezone('UTC', clock_timestamp());
        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO application_audit.au_lk_db_corrispondenze_inventory
        SELECT OLD.*, 'U', timezone('UTC', clock_timestamp());
        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO application_audit.au_lk_db_corrispondenze_inventory
        SELECT OLD.*, 'D', timezone('UTC', clock_timestamp());
        RETURN OLD;
    END IF;
    RETURN NULL;
END;
$f$;

DROP TRIGGER IF EXISTS tr_audit_lk_db_corrispondenze_inventory
    ON application_data.lk_db_corrispondenze_inventory;
CREATE TRIGGER tr_audit_lk_db_corrispondenze_inventory
    AFTER INSERT OR UPDATE OR DELETE ON application_data.lk_db_corrispondenze_inventory
    FOR EACH ROW
    EXECUTE FUNCTION application_data.fn_audit_lk_db_corrispondenze_inventory();

-- ----------------------------------------------------------------
-- 7) Guard etl_monitoring success trigger — only master lookup run
--    must drive populate_ft_quality_fpy / populate_ft_oee.
-- ----------------------------------------------------------------
CREATE OR REPLACE FUNCTION application_staging.fn_trg_etl_monitoring_after_success()
RETURNS trigger
LANGUAGE plpgsql
AS $fn$
BEGIN
    IF NEW.state = 'success' AND (OLD.state IS NULL OR OLD.state <> 'success') THEN
        IF NEW.procedure_name IS DISTINCT FROM 'application_staging.etl_run_all_lookups' THEN
            RETURN NEW;
        END IF;

        BEGIN
            CALL application_data.populate_ft_quality_fpy(
                NEW.date_min,
                NEW.date_max,
                NEW.plant_id,
                NULL::bigint,
                9999999999999::bigint,
                'ETL_SYSTEM'::varchar
            );
        EXCEPTION WHEN OTHERS THEN
            INSERT INTO application_staging.etl_log_error (error_timestamp, error_src, error_msg, error_caller)
            VALUES (
                timezone('UTC', clock_timestamp()),
                'application_staging.fn_trg_etl_monitoring_after_success.populate_ft_quality_fpy',
                SQLERRM || ' (SQLSTATE: ' || SQLSTATE || ')',
                'ETL_SYSTEM'
            );
        END;

        BEGIN
            CALL application_data.populate_ft_oee(
                NEW.date_min,
                NEW.date_max,
                NEW.plant_id,
                NULL::bigint,
                9999999999999::bigint,
                'ETL_SYSTEM'::varchar
            );
        EXCEPTION WHEN OTHERS THEN
            INSERT INTO application_staging.etl_log_error (error_timestamp, error_src, error_msg, error_caller)
            VALUES (
                timezone('UTC', clock_timestamp()),
                'application_staging.fn_trg_etl_monitoring_after_success.populate_ft_oee',
                SQLERRM || ' (SQLSTATE: ' || SQLSTATE || ')',
                'ETL_SYSTEM'
            );
        END;
    END IF;
    RETURN NEW;
END;
$fn$;

-- ----------------------------------------------------------------
-- 8) Sync: merge staging run -> LK, snapshot, clear staging for run
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE application_staging.etl_sync_db_corrispondenze_inventory(
    IN p_run_id uuid,
    IN p_plant_id bigint,
    IN p_user_id bigint,
    IN p_user_fullname varchar,
    IN p_use_etl_monitoring boolean DEFAULT true
)
LANGUAGE plpgsql
AS $proc$
-- ============================================================================================================
-- Purpose:
--   After Java loads all SharePoint sheets into db_corrispondenze_inventory for a single run_id and marks
--   inventory_ingestion_run READY_FOR_SYNC with every sheet SUCCESS, merges the full workbook snapshot
--   into application_data.lk_db_corrispondenze_inventory (insert/update/soft-delete by distinta), then
--   copies all staging rows for that run into db_corrispondenze_inventory_snapshot and deletes staging.
--
-- Call examples:
--   CALL application_staging.etl_sync_db_corrispondenze_inventory(
--       'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid, 100, 1, 'ETL Batch');
--
-- Parameters:
--   p_run_id         — UUID of the ingestion run (must match staging rows).
--   p_plant_id       — Plant scope (must match lk_plant.plant_id and staging.plant_id).
--   p_user_id        — Auditing user id for LK rows.
--   p_user_fullname  — Auditing display name.
-- ============================================================================================================
DECLARE
    lp_procedure_name   varchar(120) := 'application_staging.etl_sync_db_corrispondenze_inventory';
    lp_last_user        varchar;
    v_tz                text;
    v_local_tod         time;
    v_start_ts          timestamp := timezone('UTC', clock_timestamp());
    v_expected_sheets   int := 4;
    v_ok_sheets         int;
    v_run_status        varchar(40);
    v_staging_rows      bigint;
    v_snapshot_day_id   numeric(8);
    v_rows_updated      bigint := 0;
    v_rows_inserted     bigint := 0;
    v_rows_soft_deleted bigint := 0;
    lp_monitoring_id    bigint;
    v_plant_timezone    varchar;
    v_monitoring_open   boolean := false;
BEGIN
    IF p_user_fullname IS NULL OR p_user_id IS NULL THEN
        RAISE EXCEPTION 'p_user_id and p_user_fullname are required';
    END IF;
    lp_last_user := p_user_id::text || ' -- ' || p_user_fullname;

    INSERT INTO application_data.log_operation (
        operation_timestamp, operation_src, operation_msg, operation_caller
    ) VALUES (
        v_start_ts, lp_procedure_name,
        'Start etl_sync_db_corrispondenze_inventory run_id=' || p_run_id::text || ' plant_id=' || p_plant_id::text,
        lp_last_user
    );

    SELECT plant_timezone INTO v_tz FROM application_data.lk_plant WHERE plant_id = p_plant_id;
    IF v_tz IS NULL OR btrim(v_tz) = '' THEN
        CALL application_data.log_error_write(lp_procedure_name, 'No plant_timezone on lk_plant for plant_id=' || p_plant_id::text, lp_last_user);
        RAISE EXCEPTION 'lk_plant.plant_timezone missing for plant_id=%', p_plant_id;
    END IF;
    v_local_tod := (clock_timestamp() AT TIME ZONE v_tz)::time;
    IF NOT (v_local_tod >= time '00:00' AND v_local_tod < time '01:00') THEN
        INSERT INTO application_data.log_operation (
            operation_timestamp, operation_src, operation_msg, operation_caller
        ) VALUES (
            timezone('UTC', clock_timestamp()), lp_procedure_name,
            'Skipped: local plant time=' || v_local_tod::text
                || ' not in window 00:00-00:59 (timezone=' || v_tz || ')',
            lp_last_user
        );
        IF p_use_etl_monitoring THEN
            CALL application_staging.etl_monitoring(
                'start', lp_monitoring_id, NULL, NULL, NULL, lp_procedure_name, NULL, NULL, p_plant_id
            );
            CALL application_staging.etl_monitoring(
                'end', lp_monitoring_id, 'skipped', 'Outside 00:00-00:59 local plant window', v_tz, lp_procedure_name, NULL, NULL, p_plant_id
            );
        END IF;
        RETURN;
    END IF;

    v_plant_timezone := v_tz;
    IF p_use_etl_monitoring THEN
        CALL application_staging.etl_monitoring(
            'start', lp_monitoring_id, NULL, NULL, NULL, lp_procedure_name, NULL, NULL, p_plant_id
        );
        CALL application_staging.etl_monitoring(
            'update', lp_monitoring_id, NULL, NULL, v_plant_timezone, lp_procedure_name, NULL, NULL, p_plant_id
        );
        v_monitoring_open := true;
    END IF;

    PERFORM pg_advisory_xact_lock(hashtext(p_run_id::text));

    SELECT overall_status INTO v_run_status
    FROM application_staging.inventory_ingestion_run
    WHERE run_id = p_run_id AND plant_id = p_plant_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'inventory_ingestion_run not found for run_id=% plant_id=%', p_run_id, p_plant_id;
    END IF;

    SELECT count(*) INTO v_staging_rows
    FROM application_staging.db_corrispondenze_inventory
    WHERE run_id = p_run_id AND plant_id = p_plant_id;

    -- Idempotent retry after a successful sync (staging already cleared) or empty workbook run
    IF v_staging_rows = 0 THEN
        INSERT INTO application_data.log_operation (
            operation_timestamp, operation_src, operation_msg, operation_caller
        ) VALUES (
            timezone('UTC', clock_timestamp()), lp_procedure_name,
            'No staging rows for run_id; nothing to sync (idempotent no-op).',
            lp_last_user
        );
        IF p_use_etl_monitoring THEN
            CALL application_staging.etl_monitoring('end', lp_monitoring_id, 'success', NULL, v_plant_timezone, lp_procedure_name, NULL, NULL, p_plant_id);
        END IF;
        RETURN;
    END IF;

    IF v_run_status IS DISTINCT FROM 'READY_FOR_SYNC' THEN
        RAISE EXCEPTION 'inventory_ingestion_run.overall_status must be READY_FOR_SYNC (current=%)', v_run_status;
    END IF;

    SELECT count(*) INTO v_ok_sheets
    FROM application_staging.inventory_ingestion_run_sheet
    WHERE run_id = p_run_id AND sheet_status = 'SUCCESS';
    IF v_ok_sheets < v_expected_sheets THEN
        RAISE EXCEPTION 'Expected % SUCCESS sheets, found %', v_expected_sheets, v_ok_sheets;
    END IF;

    UPDATE application_staging.inventory_ingestion_run
    SET overall_status = 'SYNCING', updated_ts_utc = timezone('UTC', clock_timestamp())
    WHERE run_id = p_run_id;

    v_snapshot_day_id := to_char((clock_timestamp() AT TIME ZONE v_tz)::date, 'YYYYMMDD')::numeric;

    -- One read from staging (MATERIALIZED CTE), no temp table.
    WITH staging_dist AS MATERIALIZED (
        SELECT DISTINCT ON (plant_id, upper(btrim(distinta)))
            plant_id,
            btrim(distinta) AS distinta,
            descrizione,
            premontato,
            descrizione1,
            linea,
            ripetizioni,
            magazzino,
            sheet AS sheet_last,
            valid_from_day_id,
            valid_to_day_id,
            md5(
                concat_ws(
                    '|',
                    COALESCE(descrizione, ''),
                    COALESCE(premontato, ''),
                    COALESCE(descrizione1, ''),
                    COALESCE(linea, ''),
                    COALESCE(ripetizioni, ''),
                    COALESCE(magazzino, ''),
                    COALESCE(sheet, ''),
                    COALESCE(valid_from_day_id::text, ''),
                    COALESCE(valid_to_day_id::text, '')
                )
            ) AS stg_row_hash
        FROM application_staging.db_corrispondenze_inventory
        WHERE run_id = p_run_id
          AND plant_id = p_plant_id
          AND btrim(distinta) <> ''
        ORDER BY plant_id, upper(btrim(distinta)), sheet, staging_row_id
    ),
    upd_reactivate AS (
        UPDATE application_data.lk_db_corrispondenze_inventory lk
        SET
            descrizione = s.descrizione,
            premontato = s.premontato,
            descrizione1 = s.descrizione1,
            linea = s.linea,
            ripetizioni = s.ripetizioni,
            magazzino = s.magazzino,
            sheet_last = s.sheet_last,
            valid_from_day_id = s.valid_from_day_id,
            valid_to_day_id = s.valid_to_day_id,
            row_hash = s.stg_row_hash,
            is_active = true,
            is_deleted = false,
            last_modified = timezone('UTC', clock_timestamp()),
            last_user = lp_last_user
        FROM staging_dist s
        WHERE lk.plant_id = s.plant_id
          AND upper(btrim(lk.distinta)) = upper(s.distinta)
          AND (
              lk.is_deleted = true
              OR lk.row_hash IS DISTINCT FROM s.stg_row_hash
          )
        RETURNING 1
    ),
    ins_new AS (
        INSERT INTO application_data.lk_db_corrispondenze_inventory (
            plant_id, distinta, descrizione, premontato, descrizione1, linea, ripetizioni, magazzino,
            sheet_last, valid_from_day_id, valid_to_day_id, row_hash,
            is_active, is_deleted, creation_ts, creator_user, last_modified, last_user
        )
        SELECT
            s.plant_id,
            s.distinta,
            s.descrizione,
            s.premontato,
            s.descrizione1,
            s.linea,
            s.ripetizioni,
            s.magazzino,
            s.sheet_last,
            s.valid_from_day_id,
            s.valid_to_day_id,
            s.stg_row_hash,
            true,
            false,
            timezone('UTC', clock_timestamp()),
            lp_last_user,
            timezone('UTC', clock_timestamp()),
            lp_last_user
        FROM staging_dist s
        WHERE NOT EXISTS (
            SELECT 1
            FROM application_data.lk_db_corrispondenze_inventory lk
            WHERE lk.plant_id = s.plant_id
              AND upper(btrim(lk.distinta)) = upper(s.distinta)
        )
        RETURNING 1
    ),
    upd_soft_delete AS (
        UPDATE application_data.lk_db_corrispondenze_inventory lk
        SET
            is_deleted = true,
            is_active = false,
            last_modified = timezone('UTC', clock_timestamp()),
            last_user = lp_last_user
        WHERE lk.plant_id = p_plant_id
          AND lk.is_deleted = false
          AND NOT EXISTS (
              SELECT 1
              FROM staging_dist s
              WHERE s.plant_id = lk.plant_id
                AND upper(s.distinta) = upper(btrim(lk.distinta))
          )
        RETURNING 1
    )
    SELECT
        (SELECT count(*) FROM upd_reactivate),
        (SELECT count(*) FROM ins_new),
        (SELECT count(*) FROM upd_soft_delete)
    INTO
        v_rows_updated,
        v_rows_inserted,
        v_rows_soft_deleted;

    -- Snapshot + purge staging (same transaction)
    INSERT INTO application_staging.db_corrispondenze_inventory_snapshot (
        run_id, plant_id, snapshot_day_id, loaded_ts_utc,
        sheet, distinta, descrizione, premontato, descrizione1, linea, ripetizioni, magazzino,
        valid_from_day_id, valid_to_day_id
    )
    SELECT
        run_id,
        plant_id,
        v_snapshot_day_id,
        timezone('UTC', clock_timestamp()),
        sheet,
        distinta,
        descrizione,
        premontato,
        descrizione1,
        linea,
        ripetizioni,
        magazzino,
        valid_from_day_id,
        valid_to_day_id
    FROM application_staging.db_corrispondenze_inventory
    WHERE run_id = p_run_id AND plant_id = p_plant_id;

    DELETE FROM application_staging.db_corrispondenze_inventory
    WHERE run_id = p_run_id AND plant_id = p_plant_id;

    UPDATE application_staging.inventory_ingestion_run
    SET overall_status = 'SYNC_DONE', updated_ts_utc = timezone('UTC', clock_timestamp())
    WHERE run_id = p_run_id;

    INSERT INTO application_data.log_operation (
        operation_timestamp, operation_src, operation_msg, operation_caller
    ) VALUES (
        timezone('UTC', clock_timestamp()), lp_procedure_name,
        'Completed sync: snapshot_day_id=' || v_snapshot_day_id::text ||
        ' staging_rows_processed=' || v_staging_rows::text ||
        ' rows_updated=' || v_rows_updated::text ||
        ' rows_inserted=' || v_rows_inserted::text ||
        ' rows_soft_deleted=' || v_rows_soft_deleted::text,
        lp_last_user
    );

    IF p_use_etl_monitoring THEN
        CALL application_staging.etl_monitoring(
            'end', lp_monitoring_id, 'success', NULL, v_plant_timezone, lp_procedure_name, NULL, NULL, p_plant_id
        );
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        BEGIN
            UPDATE application_staging.inventory_ingestion_run
            SET overall_status = 'SYNC_FAILED', updated_ts_utc = timezone('UTC', clock_timestamp())
            WHERE run_id = p_run_id;
        EXCEPTION WHEN OTHERS THEN NULL;
        END;
        CALL application_data.log_error_write(lp_procedure_name, SQLERRM, lp_last_user);
        IF p_use_etl_monitoring AND v_monitoring_open THEN
            BEGIN
                CALL application_staging.etl_monitoring(
                    'end', lp_monitoring_id, 'failed', SQLERRM,
                    COALESCE(v_plant_timezone, v_tz), lp_procedure_name, NULL, NULL, p_plant_id
                );
            EXCEPTION WHEN OTHERS THEN NULL;
            END;
        END IF;
        RAISE;
END;
$proc$;

COMMENT ON PROCEDURE application_staging.etl_sync_db_corrispondenze_inventory(uuid, bigint, bigint, varchar, boolean) IS
    'Merge db_corrispondenze staging run into lk_db_corrispondenze_inventory; archive snapshot; clear staging. Monitoring can be delegated to a global orchestrator.';

-- ----------------------------------------------------------------
-- 9) Purge snapshot rows older than retention (chunked DELETE)
--     Run in a separate transaction after successful sync commit.
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE application_staging.purge_db_corrispondenze_inventory_snapshot_older_than(
    IN p_plant_id bigint,
    IN p_caller varchar,
    IN p_batch_size int DEFAULT 5000
)
LANGUAGE plpgsql
AS $purge$
-- ============================================================================================================
-- Purpose:
--   Deletes historical rows from db_corrispondenze_inventory_snapshot where loaded_ts_utc is older than
--   six months, using batched DELETEs to limit locking. Emits one summary row to application_data.log_operation.
--
-- Call examples:
--   CALL application_staging.purge_db_corrispondenze_inventory_snapshot_older_than(100, 'ETL_SYSTEM', 5000);
--
-- Parameters:
--   p_plant_id    — Used only for local-timezone gate (lk_plant).
--   p_caller      — Label for log_operation.operation_caller.
--   p_batch_size  — Rows per DELETE batch (ctid subquery).
-- ============================================================================================================
DECLARE
    lp_procedure_name varchar(120) := 'application_staging.purge_db_corrispondenze_inventory_snapshot_older_than';
    v_tz text;
    v_local_tod time;
    v_cutoff timestamp;
    v_deleted bigint := 0;
    v_batch int;
    v_n int;
BEGIN
    IF p_batch_size IS NULL OR p_batch_size < 1 THEN
        p_batch_size := 5000;
    END IF;

    SELECT plant_timezone INTO v_tz FROM application_data.lk_plant WHERE plant_id = p_plant_id;
    IF v_tz IS NULL OR btrim(v_tz) = '' THEN
        CALL application_data.log_error_write(lp_procedure_name, 'No plant_timezone on lk_plant for plant_id=' || p_plant_id::text, COALESCE(p_caller, 'UNKNOWN'));
        RAISE EXCEPTION 'lk_plant.plant_timezone missing for plant_id=%', p_plant_id;
    END IF;

    v_local_tod := (clock_timestamp() AT TIME ZONE v_tz)::time;
    IF NOT (v_local_tod >= time '00:00' AND v_local_tod < time '01:00') THEN
        INSERT INTO application_data.log_operation (
            operation_timestamp, operation_src, operation_msg, operation_caller
        ) VALUES (
            timezone('UTC', clock_timestamp()), lp_procedure_name,
            'Skipped purge: local time=' || v_local_tod::text
                || ' not in window 00:00-00:59 (timezone=' || v_tz || ')',
            COALESCE(p_caller, 'UNKNOWN')
        );
        RETURN;
    END IF;

    v_cutoff := timezone('UTC', clock_timestamp()) - interval '6 months';

    LOOP
        DELETE FROM application_staging.db_corrispondenze_inventory_snapshot del
        WHERE del.ctid IN (
            SELECT ctid
            FROM application_staging.db_corrispondenze_inventory_snapshot s
            WHERE s.loaded_ts_utc < v_cutoff
            LIMIT p_batch_size
        );
        GET DIAGNOSTICS v_n = ROW_COUNT;
        v_deleted := v_deleted + v_n;
        EXIT WHEN v_n = 0;
    END LOOP;

    INSERT INTO application_data.log_operation (
        operation_timestamp, operation_src, operation_msg, operation_caller
    ) VALUES (
        timezone('UTC', clock_timestamp()), lp_procedure_name,
        'Purge snapshot completed: rows_deleted=' || v_deleted::text ||
        ' cutoff_loaded_ts_utc_before=' || to_char(v_cutoff, 'YYYY-MM-DD HH24:MI:SS.MS TZ'),
        COALESCE(p_caller, 'UNKNOWN')
    );

EXCEPTION
    WHEN OTHERS THEN
        CALL application_data.log_error_write(lp_procedure_name, SQLERRM, COALESCE(p_caller, 'UNKNOWN'));
        RAISE;
END;
$purge$;

COMMENT ON PROCEDURE application_staging.purge_db_corrispondenze_inventory_snapshot_older_than(bigint, varchar, int) IS
    'Chunked delete of db_corrispondenze_inventory_snapshot older than 6 months by loaded_ts_utc; one log_operation summary.';

