-- ==============================================================
-- Script: 13_migration_inventory_kpi_coverage.sql
-- Purpose: Inventory KPI coverage model + sync + calc + KPI integration
-- Scope:   New staging/fact structures and ETL procedures for STOCKCOVER
-- ==============================================================

-- ----------------------------------------------------------------
-- 0) Inventory source placeholder
-- ----------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS inventory_remote;
-- NOTE:
-- The inventory FDW source tables (MCBA, OpenBacklog, ProductionLineData)
-- are not created in this migration because the remote inventory schema is
-- not yet available. This change set provides staging/fact structures and
-- calculation procedures so the flow can be activated later.

-- ----------------------------------------------------------------
-- 1) Run semaphore and source status
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS application_staging.inventory_kpi_run (
    run_id                 uuid PRIMARY KEY,
    plant_id               bigint NOT NULL,
    overall_status         varchar(40) NOT NULL DEFAULT 'OPEN',
    run_date_id            numeric(8) NULL,
    mcba_rows              bigint NOT NULL DEFAULT 0,
    open_backlog_rows      bigint NOT NULL DEFAULT 0,
    production_line_rows   bigint NOT NULL DEFAULT 0,
    validation_status      varchar(30) NOT NULL DEFAULT 'PENDING',
    note_msg               text NULL,
    created_ts_utc         timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    updated_ts_utc         timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    created_by             varchar NOT NULL,
    last_user              varchar NOT NULL,
    CONSTRAINT chk_inventory_kpi_run_status CHECK (
        overall_status IN ('OPEN', 'SYNCING', 'READY_FOR_CALC', 'CALCULATING', 'SUCCESS', 'FAILED')
    ),
    CONSTRAINT chk_inventory_kpi_run_validation CHECK (
        validation_status IN ('PENDING', 'VALID', 'PARTIAL', 'FAILED')
    )
);

CREATE INDEX IF NOT EXISTS idx_inventory_kpi_run_plant_status
    ON application_staging.inventory_kpi_run (plant_id, overall_status);

CREATE TABLE IF NOT EXISTS application_staging.inventory_kpi_run_source (
    run_id              uuid NOT NULL REFERENCES application_staging.inventory_kpi_run(run_id) ON DELETE CASCADE,
    source_name         varchar(100) NOT NULL,
    source_status       varchar(20) NOT NULL DEFAULT 'PENDING',
    row_count           bigint NOT NULL DEFAULT 0,
    source_note         text NULL,
    updated_ts_utc      timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    CONSTRAINT pk_inventory_kpi_run_source PRIMARY KEY (run_id, source_name),
    CONSTRAINT chk_inventory_kpi_run_source_status CHECK (
        source_status IN ('PENDING', 'RUNNING', 'SUCCESS', 'FAILED')
    )
);

-- ----------------------------------------------------------------
-- 2) Staging tables (typed structure for ETL)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS application_staging.inventory_mcba (
    staging_row_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              uuid NOT NULL,
    plant_id            bigint NOT NULL,
    werks               varchar(50) NULL,
    matnr               numeric NULL,
    lgort               varchar(50) NULL,
    dispo               varchar(50) NULL,
    dismm               varchar(50) NULL,
    mtart               varchar(50) NULL,
    matkl               varchar(50) NULL,
    gsber               varchar(50) NULL,
    spart               varchar(50) NULL,
    spmon               numeric NULL,
    mbwbest_1           numeric NULL,
    basme               varchar(50) NULL,
    wbwbest             numeric(18,2) NULL,
    huaer               varchar(50) NULL,
    bunit               numeric NULL,
    busar               varchar(50) NULL,
    erdat               timestamp NULL,
    sys_insert_date     timestamp NULL,
    day_id              numeric(8) NULL,
    loaded_ts_utc       timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp())
);
CREATE INDEX IF NOT EXISTS idx_inventory_mcba_run_plant
    ON application_staging.inventory_mcba (run_id, plant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_mcba_run_day_matnr
    ON application_staging.inventory_mcba (run_id, day_id, matnr);

CREATE TABLE IF NOT EXISTS application_staging.inventory_open_backlog (
    staging_row_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              uuid NOT NULL,
    plant_id            bigint NOT NULL,
    vbeln               numeric NULL,
    posnr               numeric NULL,
    matnr               varchar(100) NULL,
    maktx               varchar(255) NULL,
    kztlf               varchar(50) NULL,
    abgru               varchar(50) NULL,
    lifsk               varchar(50) NULL,
    data1               timestamp NULL,
    data2               timestamp NULL,
    lmeng               numeric NULL,
    vsmng1              numeric NULL,
    dispon              numeric NULL,
    stock_sp            numeric NULL,
    name1               varchar(255) NULL,
    prodh               varchar(255) NULL,
    inco1               varchar(50) NULL,
    auart               varchar(50) NULL,
    vstel               varchar(50) NULL,
    zzbabu              varchar(100) NULL,
    spediz              varchar(100) NULL,
    zzfam               varchar(100) NULL,
    zdt_origin          timestamp NULL,
    erdat               timestamp NULL,
    bunit               numeric NULL,
    busar               varchar(50) NULL,
    werks               varchar(50) NULL,
    sys_insert_date     timestamp NULL,
    ordpos              varchar(100) NULL,
    day_id              numeric(8) NULL,
    loaded_ts_utc       timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp())
);
CREATE INDEX IF NOT EXISTS idx_inventory_backlog_run_plant
    ON application_staging.inventory_open_backlog (run_id, plant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_backlog_run_day_fam
    ON application_staging.inventory_open_backlog (run_id, day_id, zzfam);

CREATE TABLE IF NOT EXISTS application_staging.inventory_line_data (
    staging_row_id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id              uuid NOT NULL,
    plant_id            bigint NOT NULL,
    mandt               numeric NULL,
    werks               varchar(50) NULL,
    zzlinea             varchar(100) NULL,
    zmacrol             varchar(100) NULL,
    zfam                varchar(100) NULL,
    zdescr              varchar(255) NULL,
    zpzlin              varchar(100) NULL,
    zlinat              varchar(100) NULL,
    zwiplin             varchar(100) NULL,
    zperlin             numeric(10,2) NULL,
    zzgg1               varchar(100) NULL,
    zzgg2               varchar(100) NULL,
    zpsatur             numeric NULL,
    astnr               numeric NULL,
    sys_insert_date     timestamp NULL,
    loaded_ts_utc       timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp())
);
CREATE INDEX IF NOT EXISTS idx_inventory_line_data_run_plant
    ON application_staging.inventory_line_data (run_id, plant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_line_data_run_keys
    ON application_staging.inventory_line_data (run_id, plant_id, werks, zfam, zzlinea);

-- Optional snapshots (day-by-day sources only)
CREATE TABLE IF NOT EXISTS application_staging.inventory_mcba_snapshot (LIKE application_staging.inventory_mcba INCLUDING DEFAULTS);
CREATE TABLE IF NOT EXISTS application_staging.inventory_open_backlog_snapshot (LIKE application_staging.inventory_open_backlog INCLUDING DEFAULTS);
CREATE INDEX IF NOT EXISTS idx_inventory_mcba_snapshot_run ON application_staging.inventory_mcba_snapshot(run_id, plant_id);
CREATE INDEX IF NOT EXISTS idx_inventory_backlog_snapshot_run ON application_staging.inventory_open_backlog_snapshot(run_id, plant_id);

-- Final master mapping from ProductionLineData (5 business columns only)
CREATE TABLE IF NOT EXISTS application_data.lk_inventory_production_line (
    werks           varchar(50) NOT NULL,
    zzlinea         varchar(100) NOT NULL,
    zmacrol         varchar(100) NOT NULL,
    zfam            varchar(100) NOT NULL,
    zdescr          varchar(255) NOT NULL,
    creation_ts     timestamp NOT NULL DEFAULT timezone('UTC', current_timestamp),
    creator_user    varchar NOT NULL,
    last_modified   timestamp NOT NULL DEFAULT timezone('UTC', current_timestamp),
    last_user       varchar NOT NULL,
    CONSTRAINT uq_lk_inventory_production_line UNIQUE (werks, zzlinea, zmacrol, zfam, zdescr)
);

-- ----------------------------------------------------------------
-- 3) Single fact for inventory coverage (premontato detail)
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS application_data.ft_inventory_coverage_premontato (
    inventory_cov_premontato_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    plant_id                    bigint NOT NULL,
    day_id                      numeric(8) NOT NULL,
    line_id                     bigint NOT NULL,
    zzlinea                     varchar(255) NOT NULL,
    premontato_code             varchar(255) NOT NULL,
    backlog_cluster_qty         numeric(20, 6) NULL,
    stock_cpf_qty               numeric(20, 6) NULL,
    stock_premontato_qty        numeric(20, 6) NULL,
    stock_totale_qty            numeric(20, 6) NULL,
    giacenza_contabile_qty      numeric(20, 6) NULL,
    giacenza_limitata_qty       numeric(20, 6) NULL,
    coverage_pct                numeric(18, 6) NULL,
    missing_qty                 numeric(20, 6) NULL,
    is_top10_missing            boolean NOT NULL DEFAULT false,
    rank_missing                integer NULL,
    calc_ts_utc                 timestamp NOT NULL DEFAULT timezone('UTC', clock_timestamp()),
    calc_run_id                 uuid NULL,
    creator_user                varchar NOT NULL,
    last_user                   varchar NOT NULL,
    CONSTRAINT pk_ft_inventory_coverage_premontato PRIMARY KEY (inventory_cov_premontato_id, plant_id, day_id),
    CONSTRAINT uq_ft_inventory_coverage_premontato UNIQUE (plant_id, day_id, line_id, zzlinea, premontato_code)
)
PARTITION BY LIST (plant_id);

CREATE INDEX IF NOT EXISTS idx_ft_inventory_coverage_premontato_day
    ON ONLY application_data.ft_inventory_coverage_premontato (day_id);
CREATE INDEX IF NOT EXISTS idx_ft_inventory_coverage_premontato_line
    ON ONLY application_data.ft_inventory_coverage_premontato (plant_id, line_id, day_id);
CREATE INDEX IF NOT EXISTS idx_ft_inventory_coverage_premontato_top10
    ON ONLY application_data.ft_inventory_coverage_premontato (plant_id, day_id, line_id, zzlinea, is_top10_missing);

-- ----------------------------------------------------------------
-- 4) Sync procedure FDW -> staging
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE application_staging.etl_sync_inventory_kpi_sources(
    INOUT p_run_id uuid,
    IN p_plant_id bigint,
    IN p_user_id bigint,
    IN p_user_fullname varchar,
    IN p_day_id numeric DEFAULT NULL,
    IN p_fdw_schema varchar DEFAULT 'inventory_remote',
    IN p_take_snapshot boolean DEFAULT true
)
LANGUAGE plpgsql
AS $proc$
DECLARE
    -- This procedure pulls MCBA/OpenBacklog/ProductionLineData rows from FDW schema
    -- into staging tables for one run_id, tracks per-source status, and optionally snapshots.
    --
    -- Example:
    --   CALL application_staging.etl_sync_inventory_kpi_sources(
    --       NULL::uuid, 100, 1, 'ETL_SYSTEM', NULL, 'inventory_remote', true
    --   );
    --   CALL application_staging.etl_sync_inventory_kpi_sources(
    --       NULL::uuid, 100, 1, 'ETL_SYSTEM', 20260324, 'inventory_remote', true
    --   );
    --
    -- Parameters:
    --   p_run_id        Existing run id for retry; NULL generates a new run.
    --   p_plant_id      Plant scope.
    --   p_user_id/name  Audit caller.
    --   p_day_id        Target source day in YYYYMMDD; if NULL defaults to previous local plant day.
    --   p_fdw_schema    FDW schema containing MCBA/OpenBacklog/ProductionLineData.
    --   p_take_snapshot If true, copies staging run to snapshot tables.
    lp_procedure_name   varchar(120) := 'application_staging.etl_sync_inventory_kpi_sources';
    lp_last_user        varchar;
    v_tz                varchar;
    v_local_time        time;
    v_sql               text;
    v_rows              bigint := 0;
    v_mcba_rows         bigint := 0;
    v_backlog_rows      bigint := 0;
    v_line_rows         bigint := 0;
    v_target_day_id     numeric(8);
    v_target_day_txt    varchar(8);
    v_validation        varchar(30) := 'VALID';
    v_note              text := '';
BEGIN
    IF p_user_id IS NULL OR p_user_fullname IS NULL THEN
        RAISE EXCEPTION 'p_user_id and p_user_fullname are required';
    END IF;
    lp_last_user := p_user_id::text || ' -- ' || p_user_fullname;

    SELECT plant_timezone INTO v_tz
    FROM application_data.lk_plant
    WHERE plant_id = p_plant_id
      AND is_deleted = false
      AND is_active = true;
    IF v_tz IS NULL OR btrim(v_tz) = '' THEN
        CALL application_data.log_error_write(lp_procedure_name, 'Missing plant timezone for plant_id=' || p_plant_id::text, lp_last_user);
        RAISE EXCEPTION 'Missing plant timezone for plant_id=%', p_plant_id;
    END IF;

    v_local_time := (NOW() AT TIME ZONE v_tz)::time;
    IF v_local_time NOT BETWEEN TIME '00:00:00' AND TIME '00:59:59' THEN
        INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
        VALUES (
            timezone('UTC', current_timestamp),
            lp_procedure_name,
            'Skipped sync: local time=' || v_local_time::text || ' for plant_id=' || p_plant_id::text ||
            ' (outside 00:00-00:59)',
            lp_last_user
        );
        RETURN;
    END IF;

    v_target_day_id := COALESCE(
        p_day_id,
        to_char(((NOW() AT TIME ZONE v_tz)::date - 1), 'YYYYMMDD')::numeric
    );
    v_target_day_txt := lpad(v_target_day_id::text, 8, '0');

    IF p_run_id IS NULL THEN
        p_run_id := md5(random()::text || clock_timestamp()::text)::uuid;
    END IF;

    INSERT INTO application_staging.inventory_kpi_run (
        run_id, plant_id, overall_status, validation_status, created_by, last_user
    )
    VALUES (
        p_run_id, p_plant_id, 'SYNCING', 'PENDING', lp_last_user, lp_last_user
    )
    ON CONFLICT (run_id) DO UPDATE
    SET overall_status = 'SYNCING',
        updated_ts_utc = timezone('UTC', clock_timestamp()),
        last_user = EXCLUDED.last_user;

    INSERT INTO application_staging.inventory_kpi_run_source (run_id, source_name, source_status)
    VALUES
        (p_run_id, 'MCBA', 'RUNNING'),
        (p_run_id, 'OpenBacklog', 'RUNNING'),
        (p_run_id, 'ProductionLineData', 'RUNNING')
    ON CONFLICT (run_id, source_name) DO UPDATE
    SET source_status = EXCLUDED.source_status,
        updated_ts_utc = timezone('UTC', clock_timestamp());

    -- MCBA (raw staging aligned to source columns)
    BEGIN
        v_sql := format($SQL$
            INSERT INTO application_staging.inventory_mcba (
                run_id, plant_id, werks, matnr, lgort, dispo, dismm, mtart, matkl, gsber,
                spart, spmon, mbwbest_1, basme, wbwbest, huaer, bunit, busar, erdat,
                sys_insert_date, day_id
            )
            SELECT
                $1::uuid,
                $2::bigint,
                UPPER(BTRIM(t.werks::text)),
                t.matnr::numeric,
                UPPER(BTRIM(t.lgort::text)),
                UPPER(BTRIM(t.dispo::text)),
                UPPER(BTRIM(t.dismm::text)),
                UPPER(BTRIM(t.mtart::text)),
                UPPER(BTRIM(t.matkl::text)),
                UPPER(BTRIM(t.gsber::text)),
                UPPER(BTRIM(t.spart::text)),
                t.spmon::numeric,
                t."mbwbest.1"::numeric,
                UPPER(BTRIM(t.basme::text)),
                t.wbwbest::numeric,
                UPPER(BTRIM(t.huaer::text)),
                t.bunit::numeric,
                UPPER(BTRIM(t.busar::text)),
                t.erdat::timestamp,
                t."sys$InsertDate"::timestamp,
                to_char(
                    t."sys$InsertDate"::date,
                    'YYYYMMDD'
                )::numeric
            FROM %I.%I t
            WHERE to_char(t."sys$InsertDate"::date, 'YYYYMMDD') = $3
              AND UPPER(BTRIM(t.werks::text)) = 'EVI'
              AND t.bunit::text = '3133'
        $SQL$, p_fdw_schema, 'MCBA');
        EXECUTE v_sql USING p_run_id, p_plant_id, v_target_day_txt;
        GET DIAGNOSTICS v_rows = ROW_COUNT;
        v_mcba_rows := COALESCE(v_rows, 0);

        UPDATE application_staging.inventory_kpi_run_source
        SET source_status = 'SUCCESS', row_count = v_mcba_rows, source_note = NULL, updated_ts_utc = timezone('UTC', clock_timestamp())
        WHERE run_id = p_run_id AND source_name = 'MCBA';
    EXCEPTION WHEN OTHERS THEN
        UPDATE application_staging.inventory_kpi_run_source
        SET source_status = 'FAILED', row_count = 0, source_note = SQLERRM, updated_ts_utc = timezone('UTC', clock_timestamp())
        WHERE run_id = p_run_id AND source_name = 'MCBA';
        v_validation := 'FAILED';
        v_note := v_note || 'MCBA failed: ' || SQLERRM || '; ';
    END;

    -- OpenBacklog (raw staging aligned to source columns)
    BEGIN
        v_sql := format($SQL$
            INSERT INTO application_staging.inventory_open_backlog (
                run_id, plant_id, vbeln, posnr, matnr, maktx, kztlf, abgru, lifsk, data1, data2,
                lmeng, vsmng1, dispon, stock_sp, name1, prodh, inco1, auart, vstel, zzbabu,
                spediz, zzfam, zdt_origin, erdat, bunit, busar, werks, sys_insert_date, ordpos,
                day_id
            )
            SELECT
                $1::uuid,
                $2::bigint,
                t."VBELN"::numeric,
                t."POSNR"::numeric,
                UPPER(BTRIM(t."MATNR"::text)),
                t."MAKTX"::text,
                UPPER(BTRIM(t."KZTLF"::text)),
                UPPER(BTRIM(t."ABGRU"::text)),
                UPPER(BTRIM(t."LIFSK"::text)),
                t."DATA1"::timestamp,
                t."DATA2"::timestamp,
                t."LMENG"::numeric,
                t."VSMNG1"::numeric,
                t."DISPON"::numeric,
                t."STOCK_SP"::numeric,
                t."NAME1"::text,
                UPPER(BTRIM(t."PRODH"::text)),
                UPPER(BTRIM(t."INCO1"::text)),
                UPPER(BTRIM(t."AUART"::text)),
                UPPER(BTRIM(t."VSTEL"::text)),
                UPPER(BTRIM(t."ZZBABU"::text)),
                UPPER(BTRIM(t."SPEDIZ"::text)),
                UPPER(BTRIM(t."ZZFAM"::text)),
                t."ZDT_ORIGIN"::timestamp,
                t."ERDAT"::timestamp,
                t."BUNIT"::numeric,
                UPPER(BTRIM(t."BUSAR"::text)),
                UPPER(BTRIM(t."WERKS"::text)),
                t."sys$InsertDate"::timestamp,
                UPPER(BTRIM(t.ordpos::text)),
                to_char(
                    t."sys$InsertDate"::date,
                    'YYYYMMDD'
                )::numeric
            FROM %I.%I t
            WHERE to_char(t."sys$InsertDate"::date, 'YYYYMMDD') = $3
              AND UPPER(BTRIM(t."WERKS"::text)) = 'EVI'
              AND t."BUNIT"::text = '3133'
        $SQL$, p_fdw_schema, 'OpenBacklog');
        EXECUTE v_sql USING p_run_id, p_plant_id, v_target_day_txt;
        GET DIAGNOSTICS v_rows = ROW_COUNT;
        v_backlog_rows := COALESCE(v_rows, 0);

        UPDATE application_staging.inventory_kpi_run_source
        SET source_status = 'SUCCESS', row_count = v_backlog_rows, source_note = NULL, updated_ts_utc = timezone('UTC', clock_timestamp())
        WHERE run_id = p_run_id AND source_name = 'OpenBacklog';
    EXCEPTION WHEN OTHERS THEN
        UPDATE application_staging.inventory_kpi_run_source
        SET source_status = 'FAILED', row_count = 0, source_note = SQLERRM, updated_ts_utc = timezone('UTC', clock_timestamp())
        WHERE run_id = p_run_id AND source_name = 'OpenBacklog';
        v_validation := 'FAILED';
        v_note := v_note || 'OpenBacklog failed: ' || SQLERRM || '; ';
    END;

    -- ProductionLineData (raw staging + merge into final master table)
    BEGIN
        v_sql := format($SQL$
            INSERT INTO application_staging.inventory_line_data (
                run_id, plant_id, mandt, werks, zzlinea, zmacrol, zfam, zdescr, zpzlin, zlinat,
                zwiplin, zperlin, zzgg1, zzgg2, zpsatur, astnr, sys_insert_date
            )
            SELECT
                $1::uuid,
                $2::bigint,
                t."MANDT"::numeric,
                UPPER(BTRIM(t."WERKS"::text)),
                UPPER(BTRIM(t."ZZLINEA"::text)),
                UPPER(BTRIM(t."ZMACROL"::text)),
                UPPER(BTRIM(t."ZFAM"::text)),
                t."ZDESCR"::text,
                UPPER(BTRIM(t."ZPZLIN"::text)),
                UPPER(BTRIM(t."ZLINAT"::text)),
                UPPER(BTRIM(t."ZWIPLIN"::text)),
                t."ZPERLIN"::numeric,
                UPPER(BTRIM(t."ZZGG1"::text)),
                UPPER(BTRIM(t."ZZGG2"::text)),
                t."ZPSATUR"::numeric,
                t."ASTNR"::numeric,
                t."sys$InsertDate"::timestamp
            FROM %I.%I t
            WHERE to_char(t."sys$InsertDate"::date, 'YYYYMMDD') = $3
              AND UPPER(BTRIM(t."WERKS"::text)) = 'EVI'
        $SQL$, p_fdw_schema, 'ProductionLineData');
        EXECUTE v_sql USING p_run_id, p_plant_id, v_target_day_txt;
        GET DIAGNOSTICS v_rows = ROW_COUNT;
        v_line_rows := COALESCE(v_rows, 0);

        INSERT INTO application_data.lk_inventory_production_line (
            werks, zzlinea, zmacrol, zfam, zdescr, creator_user, last_user
        )
        SELECT DISTINCT
            d.werks, d.zzlinea, d.zmacrol, d.zfam, d.zdescr, lp_last_user, lp_last_user
        FROM application_staging.inventory_line_data d
        WHERE d.run_id = p_run_id
          AND d.plant_id = p_plant_id
          AND d.werks = 'EVI'
          AND d.werks IS NOT NULL
          AND d.zzlinea IS NOT NULL
          AND d.zmacrol IS NOT NULL
          AND d.zfam IS NOT NULL
          AND d.zdescr IS NOT NULL
        ON CONFLICT ON CONSTRAINT uq_lk_inventory_production_line
        DO UPDATE SET
            last_modified = timezone('UTC', current_timestamp),
            last_user = EXCLUDED.last_user;

        UPDATE application_staging.inventory_kpi_run_source
        SET source_status = 'SUCCESS', row_count = v_line_rows, source_note = NULL, updated_ts_utc = timezone('UTC', clock_timestamp())
        WHERE run_id = p_run_id AND source_name = 'ProductionLineData';
    EXCEPTION WHEN OTHERS THEN
        UPDATE application_staging.inventory_kpi_run_source
        SET source_status = 'FAILED', row_count = 0, source_note = SQLERRM, updated_ts_utc = timezone('UTC', clock_timestamp())
        WHERE run_id = p_run_id AND source_name = 'ProductionLineData';
        v_validation := 'FAILED';
        v_note := v_note || 'ProductionLineData failed: ' || SQLERRM || '; ';
    END;

    IF v_validation <> 'FAILED' AND (v_mcba_rows = 0 OR v_backlog_rows = 0 OR v_line_rows = 0) THEN
        v_validation := 'PARTIAL';
        v_note := v_note || 'One or more sources are empty. ';
    ELSIF v_validation <> 'FAILED' THEN
        v_validation := 'VALID';
    END IF;

    IF p_take_snapshot THEN
        INSERT INTO application_staging.inventory_mcba_snapshot
        SELECT * FROM application_staging.inventory_mcba
        WHERE run_id = p_run_id AND plant_id = p_plant_id;

        INSERT INTO application_staging.inventory_open_backlog_snapshot
        SELECT * FROM application_staging.inventory_open_backlog
        WHERE run_id = p_run_id AND plant_id = p_plant_id;

    END IF;

    UPDATE application_staging.inventory_kpi_run
    SET overall_status = CASE WHEN v_validation = 'FAILED' THEN 'FAILED' ELSE 'READY_FOR_CALC' END,
        mcba_rows = v_mcba_rows,
        open_backlog_rows = v_backlog_rows,
        production_line_rows = v_line_rows,
        validation_status = v_validation,
        note_msg = NULLIF(v_note, ''),
        run_date_id = v_target_day_id,
        updated_ts_utc = timezone('UTC', clock_timestamp()),
        last_user = lp_last_user
    WHERE run_id = p_run_id AND plant_id = p_plant_id;

    INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
    VALUES (
        timezone('UTC', current_timestamp),
        lp_procedure_name,
        'Sync completed run_id=' || p_run_id::text || ', day_id=' || v_target_day_id::text || ', validation=' || v_validation ||
        ', rows[mcba=' || v_mcba_rows::text || ', backlog=' || v_backlog_rows::text || ', line=' || v_line_rows::text || ']',
        lp_last_user
    );

EXCEPTION
    WHEN OTHERS THEN
        UPDATE application_staging.inventory_kpi_run
        SET overall_status = 'FAILED',
            validation_status = 'FAILED',
            note_msg = COALESCE(note_msg, '') || ' fatal: ' || SQLERRM,
            updated_ts_utc = timezone('UTC', clock_timestamp())
        WHERE run_id = p_run_id AND plant_id = p_plant_id;
        CALL application_data.log_error_write(lp_procedure_name, SQLERRM, COALESCE(lp_last_user, 'UNKNOWN'));
        RAISE;
END;
$proc$;

-- ----------------------------------------------------------------
-- 7) Global inventory orchestrator (db_corrispondenze + KPI coverage)
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE application_staging.etl_run_inventory_full(
    INOUT p_run_id uuid,
    IN p_plant_id bigint,
    IN p_user_id bigint,
    IN p_user_fullname varchar,
    IN p_day_id numeric DEFAULT NULL,
    IN p_fdw_schema varchar DEFAULT 'inventory_remote',
    IN p_take_snapshot boolean DEFAULT true,
    IN p_run_purge boolean DEFAULT true,
    IN p_purge_blocking boolean DEFAULT false,
    IN p_purge_batch_size int DEFAULT 5000
)
LANGUAGE plpgsql
AS $proc$
DECLARE
    -- This orchestrator is the single owner of etl_monitoring lifecycle for the
    -- full inventory block: db_corrispondenze sync (change 12) + KPI coverage (change 13).
    --
    -- Example:
    --   CALL application_staging.etl_run_inventory_full(
    --       'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid,
    --       100, 1, 'ETL_SYSTEM', 20260324, 'inventory_remote', true, true, false, 5000
    --   );
    lp_procedure_name      varchar(120) := 'application_staging.etl_run_inventory_full';
    lp_last_user           varchar;
    lp_monitoring_id       bigint;
    v_monitoring_open      boolean := false;
    v_tz                   varchar;
    v_local_time           time;
    v_ingestion_status     varchar(40);
    v_kpi_status           varchar(40);
    v_kpi_validation       varchar(30);
    v_end_note             text := NULL;
BEGIN
    IF p_user_id IS NULL OR p_user_fullname IS NULL THEN
        RAISE EXCEPTION 'p_user_id and p_user_fullname are required';
    END IF;
    lp_last_user := p_user_id::text || ' -- ' || p_user_fullname;

    SELECT plant_timezone INTO v_tz
    FROM application_data.lk_plant
    WHERE plant_id = p_plant_id
      AND is_deleted = false
      AND is_active = true;
    IF v_tz IS NULL OR btrim(v_tz) = '' THEN
        CALL application_data.log_error_write(lp_procedure_name, 'Missing plant timezone for plant_id=' || p_plant_id::text, lp_last_user);
        RAISE EXCEPTION 'Missing plant timezone for plant_id=%', p_plant_id;
    END IF;

    v_local_time := (NOW() AT TIME ZONE v_tz)::time;
    IF v_local_time NOT BETWEEN TIME '00:00:00' AND TIME '00:59:59' THEN
        CALL application_staging.etl_monitoring(
            'start', lp_monitoring_id, NULL, NULL, NULL, lp_procedure_name, NULL, NULL, p_plant_id
        );
        CALL application_staging.etl_monitoring(
            'end', lp_monitoring_id, 'skipped', 'Outside 00:00-00:59 local plant window', v_tz, lp_procedure_name, NULL, NULL, p_plant_id
        );
        INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
        VALUES (
            timezone('UTC', current_timestamp),
            lp_procedure_name,
            'Skipped full inventory run: local time=' || v_local_time::text || ' for plant_id=' || p_plant_id::text,
            lp_last_user
        );
        RETURN;
    END IF;

    CALL application_staging.etl_monitoring(
        'start', lp_monitoring_id, NULL, NULL, NULL, lp_procedure_name, NULL, NULL, p_plant_id
    );
    CALL application_staging.etl_monitoring(
        'update', lp_monitoring_id, NULL, 'phase=db_corrispondenze_sync', v_tz, lp_procedure_name, NULL, NULL, p_plant_id
    );
    v_monitoring_open := true;

    CALL application_staging.etl_sync_db_corrispondenze_inventory(
        p_run_id,
        p_plant_id,
        p_user_id,
        p_user_fullname,
        false
    );

    SELECT overall_status
    INTO v_ingestion_status
    FROM application_staging.inventory_ingestion_run
    WHERE run_id = p_run_id
      AND plant_id = p_plant_id;
    IF COALESCE(v_ingestion_status, '') NOT IN ('SYNC_DONE', 'READY_FOR_SYNC') THEN
        RAISE EXCEPTION 'db_corrispondenze sync ended with unexpected status % for run_id=%', v_ingestion_status, p_run_id;
    END IF;

    CALL application_staging.etl_monitoring(
        'update', lp_monitoring_id, NULL, 'phase=inventory_kpi_sync_calc', v_tz, lp_procedure_name, NULL, NULL, p_plant_id
    );

    CALL application_staging.etl_run_inventory_kpi(
        p_run_id,
        p_plant_id,
        p_user_id,
        p_user_fullname,
        p_day_id,
        p_fdw_schema,
        p_take_snapshot
    );

    SELECT overall_status, validation_status
    INTO v_kpi_status, v_kpi_validation
    FROM application_staging.inventory_kpi_run
    WHERE run_id = p_run_id
      AND plant_id = p_plant_id;
    IF COALESCE(v_kpi_status, '') <> 'SUCCESS' THEN
        RAISE EXCEPTION 'inventory KPI block ended with status % (validation=%) for run_id=%',
            v_kpi_status, COALESCE(v_kpi_validation, 'NULL'), p_run_id;
    END IF;

    IF p_run_purge THEN
        CALL application_staging.etl_monitoring(
            'update', lp_monitoring_id, NULL, 'phase=purge_snapshot', v_tz, lp_procedure_name, NULL, NULL, p_plant_id
        );
        BEGIN
            CALL application_staging.purge_db_corrispondenze_inventory_snapshot_older_than(
                p_plant_id,
                lp_last_user,
                p_purge_batch_size
            );
        EXCEPTION WHEN OTHERS THEN
            IF p_purge_blocking THEN
                RAISE;
            END IF;
            v_end_note := COALESCE(v_end_note, '') || 'purge_warning=' || SQLERRM;
            INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
            VALUES (
                timezone('UTC', current_timestamp),
                lp_procedure_name,
                'Non-blocking purge warning for run_id=' || p_run_id::text || ': ' || SQLERRM,
                lp_last_user
            );
        END;
    END IF;

    CALL application_staging.etl_monitoring(
        'end', lp_monitoring_id, 'success', NULLIF(v_end_note, ''), v_tz, lp_procedure_name, NULL, NULL, p_plant_id
    );
    v_monitoring_open := false;

    INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
    VALUES (
        timezone('UTC', current_timestamp),
        lp_procedure_name,
        'Full inventory run completed for plant_id=' || p_plant_id::text || ', run_id=' || p_run_id::text ||
        ', kpi_validation=' || COALESCE(v_kpi_validation, 'NULL'),
        lp_last_user
    );

EXCEPTION
    WHEN OTHERS THEN
        IF v_monitoring_open THEN
            BEGIN
                CALL application_staging.etl_monitoring(
                    'end', lp_monitoring_id, 'failed', SQLERRM, COALESCE(v_tz, 'UTC'), lp_procedure_name, NULL, NULL, p_plant_id
                );
            EXCEPTION WHEN OTHERS THEN NULL;
            END;
        END IF;
        CALL application_data.log_error_write(lp_procedure_name, SQLERRM, COALESCE(lp_last_user, 'UNKNOWN'));
        RAISE;
END;
$proc$;

-- ----------------------------------------------------------------
-- 5) Coverage calculation procedure + KPI integration
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE application_data.populate_ft_inventory_coverage(
    IN p_run_id uuid,
    IN p_plant_id bigint,
    IN p_user_id bigint,
    IN p_user_fullname varchar
)
LANGUAGE plpgsql
AS $proc$
DECLARE
    -- This procedure computes inventory coverage at premontato and logical-line levels
    -- using a double MCBA pass (CPF + premontato), then updates STOCKCOVER in ft_kpi_target
    -- only at final line/day level.
    --
    -- Example:
    --   CALL application_data.populate_ft_inventory_coverage(
    --       'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid, 100, 1, 'ETL_SYSTEM'
    --   );
    --
    -- Parameters:
    --   p_run_id        Source run_id prepared by etl_sync_inventory_kpi_sources.
    --   p_plant_id      Plant scope.
    --   p_user_id/name  Audit caller.
    lp_procedure_name   varchar(120) := 'application_data.populate_ft_inventory_coverage';
    lp_last_user        varchar;
    v_tz                varchar;
    v_local_time        time;
    v_run_status        varchar(40);
    v_validation        varchar(30);
    v_day_min           numeric(8);
    v_day_max           numeric(8);
    v_month_cursor      date;
    v_month_end         date;
    v_year              int;
    v_month             int;
    v_kpi_id            bigint;
    v_rows_prem         bigint := 0;
    v_rows_kpi_upd      bigint := 0;
BEGIN
    IF p_user_id IS NULL OR p_user_fullname IS NULL THEN
        RAISE EXCEPTION 'p_user_id and p_user_fullname are required';
    END IF;
    lp_last_user := p_user_id::text || ' -- ' || p_user_fullname;

    SELECT plant_timezone INTO v_tz
    FROM application_data.lk_plant
    WHERE plant_id = p_plant_id
      AND is_deleted = false
      AND is_active = true;
    IF v_tz IS NULL OR btrim(v_tz) = '' THEN
        CALL application_data.log_error_write(lp_procedure_name, 'Missing plant timezone for plant_id=' || p_plant_id::text, lp_last_user);
        RAISE EXCEPTION 'Missing plant timezone for plant_id=%', p_plant_id;
    END IF;

    v_local_time := (NOW() AT TIME ZONE v_tz)::time;
    IF v_local_time NOT BETWEEN TIME '00:00:00' AND TIME '00:59:59' THEN
        INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
        VALUES (
            timezone('UTC', current_timestamp),
            lp_procedure_name,
            'Skipped calc: local time=' || v_local_time::text || ' for plant_id=' || p_plant_id::text ||
            ' (outside 00:00-00:59)',
            lp_last_user
        );
        RETURN;
    END IF;

    SELECT overall_status, validation_status
    INTO v_run_status, v_validation
    FROM application_staging.inventory_kpi_run
    WHERE run_id = p_run_id
      AND plant_id = p_plant_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'inventory_kpi_run not found for run_id=% plant_id=%', p_run_id, p_plant_id;
    END IF;
    IF v_run_status NOT IN ('READY_FOR_CALC', 'SUCCESS') THEN
        RAISE EXCEPTION 'run status % cannot be processed', v_run_status;
    END IF;

    SELECT min(day_id), max(day_id)
    INTO v_day_min, v_day_max
    FROM application_staging.inventory_open_backlog
    WHERE run_id = p_run_id
      AND plant_id = p_plant_id;

    IF v_day_min IS NULL OR v_day_max IS NULL THEN
        UPDATE application_staging.inventory_kpi_run
        SET overall_status = 'FAILED',
            validation_status = 'FAILED',
            note_msg = COALESCE(note_msg, '') || ' Missing day_id range: no backlog dates found for the current run.',
            updated_ts_utc = timezone('UTC', clock_timestamp()),
            last_user = lp_last_user
        WHERE run_id = p_run_id AND plant_id = p_plant_id;
        RETURN;
    END IF;

    -- Mandatory plant list partition checks
    BEGIN
        PERFORM application_data.create_plant_partition('ft_inventory_coverage_premontato', 'day_id', p_plant_id);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLSTATE IN ('42P07', 'P0001') THEN
                INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
                VALUES (timezone('UTC', current_timestamp), lp_procedure_name, 'Plant partition ft_inventory_coverage_premontato_plant_' || p_plant_id::text || ' already exists, continuing.', lp_last_user);
            ELSE
                CALL application_data.log_error_write(lp_procedure_name, 'create_plant_partition(ft_inventory_coverage_premontato) failed for plant_id=' || p_plant_id::text || ': ' || SQLERRM, lp_last_user);
            END IF;
    END;

    BEGIN
        PERFORM application_data.create_plant_partition('ft_kpi_target', 'target_date_iso', p_plant_id);
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLSTATE IN ('42P07', 'P0001') THEN
                INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
                VALUES (timezone('UTC', current_timestamp), lp_procedure_name, 'Plant partition ft_kpi_target_plant_' || p_plant_id::text || ' already exists, continuing.', lp_last_user);
            ELSE
                CALL application_data.log_error_write(lp_procedure_name, 'create_plant_partition(ft_kpi_target) failed for plant_id=' || p_plant_id::text || ': ' || SQLERRM, lp_last_user);
            END IF;
    END;

    -- Monthly partitions for full run range
    v_month_cursor := date_trunc('month', to_date(v_day_min::text, 'YYYYMMDD'))::date;
    v_month_end := date_trunc('month', to_date(v_day_max::text, 'YYYYMMDD'))::date;
    WHILE v_month_cursor <= v_month_end LOOP
        v_year := extract(year from v_month_cursor)::int;
        v_month := extract(month from v_month_cursor)::int;
        BEGIN
            PERFORM application_data.create_monthly_partition('ft_inventory_coverage_premontato', 'day_id', p_plant_id, v_year, v_month);
        EXCEPTION WHEN OTHERS THEN
            IF SQLSTATE <> '42P07' THEN
                CALL application_data.log_error_write(lp_procedure_name, 'create_monthly_partition(ft_inventory_coverage_premontato) failed for plant_id=' || p_plant_id::text || ', ' || v_year::text || '-' || lpad(v_month::text, 2, '0') || ': ' || SQLERRM, lp_last_user);
            END IF;
        END;
        BEGIN
            PERFORM application_data.create_monthly_partition('ft_kpi_target', 'target_date_iso', p_plant_id, v_year, v_month);
        EXCEPTION WHEN OTHERS THEN
            IF SQLSTATE <> '42P07' THEN
                CALL application_data.log_error_write(lp_procedure_name, 'create_monthly_partition(ft_kpi_target) failed for plant_id=' || p_plant_id::text || ', ' || v_year::text || '-' || lpad(v_month::text, 2, '0') || ': ' || SQLERRM, lp_last_user);
            END IF;
        END;
        v_month_cursor := (v_month_cursor + interval '1 month')::date;
    END LOOP;

    -- Coverage detail (double MCBA pass + top10)
    -- Backlog metric is day-based: class from (zdt_origin, sys_insert_date),
    -- then SUM(VSMNG1) only for classes Scaduto and Scadere10.
    WITH line_scope AS (
        SELECT DISTINCT
            ln.line_id,
            upper(btrim(ln.line_code_inv)) AS line_code_inv
        FROM application_data.lk_line ln
        WHERE ln.plant_id = p_plant_id
          AND ln.is_deleted = false
          AND ln.is_active = true
          AND btrim(COALESCE(ln.line_code_inv, '')) <> ''
    ),
    logical_line_scope AS (
        SELECT DISTINCT
            ls.line_id,
            upper(btrim(pl.zzlinea)) AS zzlinea,
            ls.line_code_inv
        FROM line_scope ls
        JOIN application_data.lk_inventory_production_line pl
          ON upper(btrim(pl.zfam)) = ls.line_code_inv
         AND upper(btrim(pl.werks)) = 'EVI'
    ),
    corr_scope AS (
        SELECT DISTINCT
            lls.line_id,
            lls.zzlinea,
            upper(btrim(corr.distinta)) AS cpf_code
        FROM logical_line_scope lls
        JOIN application_data.lk_db_corrispondenze_inventory corr
          ON corr.plant_id = p_plant_id
         AND corr.is_deleted = false
         AND corr.is_active = true
         AND upper(btrim(corr.linea)) = lls.zzlinea
        WHERE btrim(COALESCE(corr.distinta, '')) <> ''
    ),
    open_backlog_cluster AS (
        SELECT
            ob.day_id,
            cs.line_id,
            cs.zzlinea,
            cs.cpf_code,
            CASE
                WHEN ob.zdt_origin IS NULL OR ob.sys_insert_date IS NULL THEN 'FUORI_ORIZZONTE'
                WHEN ob.zdt_origin < ob.sys_insert_date THEN 'SCADUTO'
                WHEN ob.zdt_origin < (ob.sys_insert_date + INTERVAL '11 day') THEN 'SCADERE10'
                ELSE 'FUORI_ORIZZONTE'
            END AS backlog_cluster_type,
            COALESCE(ob.vsmng1, 0) AS backlog_qty
        FROM application_staging.inventory_open_backlog ob
        JOIN corr_scope cs
          ON upper(btrim(ob.matnr)) = cs.cpf_code
        WHERE ob.run_id = p_run_id
          AND ob.plant_id = p_plant_id
          AND upper(btrim(ob.werks)) = 'EVI'
          AND ob.bunit::text = '3133'
          AND ob.day_id BETWEEN v_day_min AND v_day_max
    ),
    backlog_norm AS (
        SELECT
            day_id,
            line_id,
            zzlinea,
            cpf_code,
            SUM(
                CASE
                    WHEN backlog_cluster_type IN ('SCADUTO', 'SCADERE10') THEN backlog_qty
                    ELSE 0
                END
            ) AS backlog_cluster_qty
        FROM open_backlog_cluster
        GROUP BY day_id, line_id, zzlinea, cpf_code
    ),
    corr_prem_mag AS (
        SELECT DISTINCT
            bn.day_id,
            bn.line_id,
            bn.zzlinea,
            bn.cpf_code,
            upper(btrim(corr.premontato)) AS premontato_code,
            upper(btrim(corr.magazzino)) AS magazzino
        FROM backlog_norm bn
        JOIN application_data.lk_db_corrispondenze_inventory corr
          ON corr.plant_id = p_plant_id
         AND corr.is_deleted = false
         AND corr.is_active = true
         AND upper(btrim(corr.linea)) = bn.zzlinea
         AND upper(btrim(corr.distinta)) = bn.cpf_code
        WHERE btrim(COALESCE(corr.premontato, '')) <> ''
          AND btrim(COALESCE(corr.magazzino, '')) <> ''
    ),
    mcba_cpf_scope AS (
        SELECT DISTINCT
            bn.day_id,
            bn.line_id,
            bn.zzlinea,
            bn.cpf_code
        FROM backlog_norm bn
    ),
    mcba_cpf AS (
        SELECT
            m.day_id,
            sc.line_id,
            sc.zzlinea,
            upper(btrim(m.matnr::text)) AS cpf_code,
            SUM(COALESCE(m.mbwbest_1, 0)) AS stock_cpf_qty
        FROM application_staging.inventory_mcba m
        JOIN mcba_cpf_scope sc
          ON sc.day_id = m.day_id
         AND sc.cpf_code = upper(btrim(m.matnr::text))
        WHERE m.run_id = p_run_id
          AND m.plant_id = p_plant_id
          AND upper(btrim(m.werks)) = 'EVI'
          AND m.bunit::text = '3133'
          AND upper(btrim(m.lgort)) IN ('SPO2', 'SPD3', 'ENT2', 'SPOM')
        GROUP BY m.day_id, sc.line_id, sc.zzlinea, upper(btrim(m.matnr::text))
    ),
    mcba_prem_scope AS (
        SELECT DISTINCT
            cpm.day_id,
            cpm.line_id,
            cpm.zzlinea,
            upper(btrim(cpm.premontato_code)) AS premontato_code,
            upper(btrim(cpm.magazzino)) AS lgort
        FROM corr_prem_mag cpm
    ),
    mcba_prem AS (
        SELECT
            m.day_id,
            sc.line_id,
            sc.zzlinea,
            upper(btrim(m.matnr::text)) AS premontato_code,
            upper(btrim(m.lgort::text)) AS lgort,
            SUM(COALESCE(m.mbwbest_1, 0)) AS stock_premontato_qty
        FROM application_staging.inventory_mcba m
        JOIN mcba_prem_scope sc
          ON sc.day_id = m.day_id
         AND sc.premontato_code = upper(btrim(m.matnr::text))
         AND sc.lgort = upper(btrim(m.lgort::text))
        WHERE m.run_id = p_run_id
          AND m.plant_id = p_plant_id
          AND upper(btrim(m.werks)) = 'EVI'
          AND m.bunit::text = '3133'
        GROUP BY m.day_id, sc.line_id, sc.zzlinea, upper(btrim(m.matnr::text)), upper(btrim(m.lgort::text))
    ),
    detail_raw AS (
        SELECT
            p_plant_id AS plant_id,
            b.day_id,
            b.line_id,
            b.zzlinea,
            upper(btrim(cpm.premontato_code)) AS premontato_code,
            SUM(COALESCE(b.backlog_cluster_qty, 0)) AS backlog_cluster_qty,
            SUM(COALESCE(cpf.stock_cpf_qty, 0)) AS stock_cpf_qty,
            SUM(COALESCE(prem.stock_premontato_qty, 0)) AS stock_premontato_qty
        FROM backlog_norm b
        JOIN corr_prem_mag cpm
          ON cpm.day_id = b.day_id
         AND cpm.line_id = b.line_id
         AND cpm.zzlinea = b.zzlinea
         AND cpm.cpf_code = b.cpf_code
        LEFT JOIN mcba_cpf cpf
          ON cpf.day_id = b.day_id
         AND cpf.line_id = b.line_id
         AND cpf.zzlinea = b.zzlinea
         AND cpf.cpf_code = upper(btrim(b.cpf_code))
        LEFT JOIN mcba_prem prem
          ON prem.day_id = b.day_id
         AND prem.line_id = b.line_id
         AND prem.zzlinea = b.zzlinea
         AND prem.premontato_code = upper(btrim(cpm.premontato_code))
         AND prem.lgort = upper(btrim(cpm.magazzino))
        WHERE b.line_id IS NOT NULL
          AND cpm.premontato_code IS NOT NULL
        GROUP BY p_plant_id, b.day_id, b.line_id, b.zzlinea, upper(btrim(cpm.premontato_code))
    ),
    ranked AS (
        SELECT
            d.*,
            (COALESCE(d.stock_cpf_qty, 0) + COALESCE(d.stock_premontato_qty, 0)) AS stock_totale_qty,
            (COALESCE(d.stock_cpf_qty, 0) + COALESCE(d.stock_premontato_qty, 0)) AS giacenza_contabile_qty,
            LEAST(
                (COALESCE(d.stock_cpf_qty, 0) + COALESCE(d.stock_premontato_qty, 0)),
                COALESCE(d.backlog_cluster_qty, 0)
            ) AS giacenza_limitata_qty,
            CASE
                WHEN COALESCE(d.backlog_cluster_qty, 0) <= 0 THEN 100::numeric
                ELSE round(greatest(0::numeric, least(100::numeric,
                    (
                        LEAST(
                            (COALESCE(d.stock_cpf_qty, 0) + COALESCE(d.stock_premontato_qty, 0)),
                            COALESCE(d.backlog_cluster_qty, 0)
                        ) / NULLIF(d.backlog_cluster_qty, 0)
                    ) * 100
                )), 6)
            END AS coverage_pct,
            greatest(
                COALESCE(d.backlog_cluster_qty, 0) -
                LEAST(
                    (COALESCE(d.stock_cpf_qty, 0) + COALESCE(d.stock_premontato_qty, 0)),
                    COALESCE(d.backlog_cluster_qty, 0)
                ),
                0
            ) AS missing_qty
        FROM detail_raw d
    ),
    ranked_top AS (
        SELECT
            r.*,
            row_number() OVER (
                PARTITION BY r.plant_id, r.day_id, r.line_id, r.zzlinea
                ORDER BY r.missing_qty DESC, r.premontato_code
            ) AS rank_missing
        FROM ranked r
    ),
    upsert_prem AS (
        INSERT INTO application_data.ft_inventory_coverage_premontato (
            plant_id, day_id, line_id, zzlinea, premontato_code,
            backlog_cluster_qty, stock_cpf_qty, stock_premontato_qty, stock_totale_qty,
            giacenza_contabile_qty, giacenza_limitata_qty,
            coverage_pct, missing_qty, is_top10_missing, rank_missing,
            calc_ts_utc, calc_run_id, creator_user, last_user
        )
        SELECT
            plant_id, day_id, line_id, zzlinea, premontato_code,
            backlog_cluster_qty, stock_cpf_qty, stock_premontato_qty, stock_totale_qty,
            giacenza_contabile_qty, giacenza_limitata_qty,
            coverage_pct, missing_qty, (rank_missing <= 10), rank_missing,
            timezone('UTC', clock_timestamp()), p_run_id, lp_last_user, lp_last_user
        FROM ranked_top
        ON CONFLICT ON CONSTRAINT uq_ft_inventory_coverage_premontato
        DO UPDATE SET
            backlog_cluster_qty = EXCLUDED.backlog_cluster_qty,
            stock_cpf_qty = EXCLUDED.stock_cpf_qty,
            stock_premontato_qty = EXCLUDED.stock_premontato_qty,
            stock_totale_qty = EXCLUDED.stock_totale_qty,
            giacenza_contabile_qty = EXCLUDED.giacenza_contabile_qty,
            giacenza_limitata_qty = EXCLUDED.giacenza_limitata_qty,
            coverage_pct = EXCLUDED.coverage_pct,
            missing_qty = EXCLUDED.missing_qty,
            is_top10_missing = EXCLUDED.is_top10_missing,
            rank_missing = EXCLUDED.rank_missing,
            calc_ts_utc = EXCLUDED.calc_ts_utc,
            calc_run_id = EXCLUDED.calc_run_id,
            last_user = EXCLUDED.last_user
        RETURNING 1
    )
    SELECT count(*) INTO v_rows_prem FROM upsert_prem;

    -- KPI integration (final line/day only)
    SELECT kpi_id INTO v_kpi_id
    FROM application_data.lk_kpi
    WHERE plant_id = p_plant_id
      AND upper(kpi_code) = 'STOCKCOVER'
      AND is_deleted = false
    LIMIT 1;

    IF v_kpi_id IS NULL THEN
        CALL application_data.log_error_write(lp_procedure_name, 'KPI code STOCKCOVER not found for plant_id=' || p_plant_id::text, lp_last_user);
        RAISE EXCEPTION 'KPI STOCKCOVER not configured for plant_id=%', p_plant_id;
    END IF;

    -- Update KPI final value line/day from runtime aggregation on detail fact
    WITH line_day_kpi AS (
        SELECT
            plant_id,
            day_id,
            line_id,
            CASE
                WHEN sum(COALESCE(backlog_cluster_qty, 0)) <= 0 THEN 100::numeric
                ELSE round(greatest(0::numeric, least(100::numeric,
                    (sum(COALESCE(giacenza_limitata_qty, 0)) / NULLIF(sum(backlog_cluster_qty), 0)) * 100
                )), 6)
            END AS line_coverage_pct
        FROM application_data.ft_inventory_coverage_premontato
        WHERE plant_id = p_plant_id
          AND day_id BETWEEN v_day_min AND v_day_max
          AND calc_run_id = p_run_id
        GROUP BY plant_id, day_id, line_id
    )
    UPDATE application_data.ft_kpi_target tgt
    SET
        kpi_value = src.line_coverage_pct,
        last_modified = timezone('UTC', current_timestamp),
        last_user = lp_last_user
    FROM line_day_kpi src
    WHERE tgt.plant_id = src.plant_id
      AND tgt.kpi_id = v_kpi_id
      AND tgt.line_id = src.line_id
      AND tgt.target_date_iso = src.day_id;
    GET DIAGNOSTICS v_rows_kpi_upd = ROW_COUNT;

    -- Missing-source marker: only impacted line/day where STOCKCOVER baseline exists but no computed value
    IF v_validation = 'PARTIAL' THEN
        WITH expected_line_day AS (
            SELECT DISTINCT
                d.day_id,
                a.line_id
            FROM (
                SELECT DISTINCT day_id
                FROM application_staging.inventory_open_backlog
                WHERE run_id = p_run_id
                  AND plant_id = p_plant_id
                  AND day_id BETWEEN v_day_min AND v_day_max
            ) d
            JOIN application_data.ass_module_line_tier_kpi a
              ON a.plant_id = p_plant_id
             AND a.kpi_id = v_kpi_id
             AND a.is_active = true
             AND a.is_deleted = false
        ),
        computed_line_day AS (
            SELECT DISTINCT day_id, line_id
            FROM application_data.ft_inventory_coverage_premontato
            WHERE plant_id = p_plant_id
              AND day_id BETWEEN v_day_min AND v_day_max
              AND calc_run_id = p_run_id
        ),
        impacted_line_day AS (
            SELECT e.day_id, e.line_id
            FROM expected_line_day e
            LEFT JOIN computed_line_day c
              ON c.day_id = e.day_id
             AND c.line_id = e.line_id
            WHERE c.day_id IS NULL
        )
        UPDATE application_data.ft_kpi_target tgt
        SET
            kpi_value = -100,
            last_modified = timezone('UTC', current_timestamp),
            last_user = lp_last_user
        FROM impacted_line_day imp
        WHERE tgt.plant_id = p_plant_id
          AND tgt.kpi_id = v_kpi_id
          AND tgt.line_id = imp.line_id
          AND tgt.target_date_iso = imp.day_id;
    END IF;

    UPDATE application_staging.inventory_kpi_run
    SET overall_status = 'SUCCESS',
        validation_status = v_validation,
        updated_ts_utc = timezone('UTC', clock_timestamp()),
        last_user = lp_last_user
    WHERE run_id = p_run_id AND plant_id = p_plant_id;

    INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
    VALUES (
        timezone('UTC', current_timestamp),
        lp_procedure_name,
        'Calc completed run_id=' || p_run_id::text ||
        ', rows[prem=' || v_rows_prem::text ||
        ', kpi_updated=' || v_rows_kpi_upd::text || ']',
        lp_last_user
    );

EXCEPTION
    WHEN OTHERS THEN
        UPDATE application_staging.inventory_kpi_run
        SET overall_status = 'FAILED',
            validation_status = 'FAILED',
            note_msg = COALESCE(note_msg, '') || ' calc fatal: ' || SQLERRM,
            updated_ts_utc = timezone('UTC', clock_timestamp())
        WHERE run_id = p_run_id AND plant_id = p_plant_id;
        CALL application_data.log_error_write(lp_procedure_name, SQLERRM, COALESCE(lp_last_user, 'UNKNOWN'));
        RAISE;
END;
$proc$;

-- ----------------------------------------------------------------
-- 6) Orchestrator
-- ----------------------------------------------------------------
CREATE OR REPLACE PROCEDURE application_staging.etl_run_inventory_kpi(
    INOUT p_run_id uuid,
    IN p_plant_id bigint,
    IN p_user_id bigint,
    IN p_user_fullname varchar,
    IN p_day_id numeric DEFAULT NULL,
    IN p_fdw_schema varchar DEFAULT 'inventory_remote',
    IN p_take_snapshot boolean DEFAULT true
)
LANGUAGE plpgsql
AS $proc$
DECLARE
    -- This orchestrator executes the complete inventory KPI flow:
    -- source sync (FDW -> staging) and coverage calculation/KPI writeback.
    --
    -- Example:
    --   CALL application_staging.etl_run_inventory_kpi(
    --       NULL::uuid, 100, 1, 'ETL_SYSTEM', NULL, 'inventory_remote', true
    --   );
    --   CALL application_staging.etl_run_inventory_kpi(
    --       NULL::uuid, 100, 1, 'ETL_SYSTEM', 20260324, 'inventory_remote', true
    --   );
    lp_procedure_name   varchar(120) := 'application_staging.etl_run_inventory_kpi';
    lp_last_user        varchar;
    v_tz                varchar;
    v_local_time        time;
BEGIN
    IF p_user_id IS NULL OR p_user_fullname IS NULL THEN
        RAISE EXCEPTION 'p_user_id and p_user_fullname are required';
    END IF;
    lp_last_user := p_user_id::text || ' -- ' || p_user_fullname;

    SELECT plant_timezone INTO v_tz
    FROM application_data.lk_plant
    WHERE plant_id = p_plant_id
      AND is_deleted = false
      AND is_active = true;
    IF v_tz IS NULL OR btrim(v_tz) = '' THEN
        CALL application_data.log_error_write(lp_procedure_name, 'Missing plant timezone for plant_id=' || p_plant_id::text, lp_last_user);
        RAISE EXCEPTION 'Missing plant timezone for plant_id=%', p_plant_id;
    END IF;

    v_local_time := (NOW() AT TIME ZONE v_tz)::time;
    IF v_local_time NOT BETWEEN TIME '00:00:00' AND TIME '00:59:59' THEN
        INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
        VALUES (
            timezone('UTC', current_timestamp),
            lp_procedure_name,
            'Skipped run: local time=' || v_local_time::text || ' for plant_id=' || p_plant_id::text ||
            ' (outside 00:00-00:59)',
            lp_last_user
        );
        RETURN;
    END IF;

    INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
    VALUES (
        timezone('UTC', current_timestamp),
        lp_procedure_name,
        'Start run for plant_id=' || p_plant_id::text,
        lp_last_user
    );

    CALL application_staging.etl_sync_inventory_kpi_sources(
        p_run_id,
        p_plant_id,
        p_user_id,
        p_user_fullname,
        p_day_id,
        p_fdw_schema,
        p_take_snapshot
    );

    CALL application_data.populate_ft_inventory_coverage(
        p_run_id,
        p_plant_id,
        p_user_id,
        p_user_fullname
    );

    INSERT INTO application_data.log_operation(operation_timestamp, operation_src, operation_msg, operation_caller)
    VALUES (
        timezone('UTC', current_timestamp),
        lp_procedure_name,
        'Run completed for plant_id=' || p_plant_id::text || ', run_id=' || p_run_id::text,
        lp_last_user
    );

EXCEPTION
    WHEN OTHERS THEN
        CALL application_data.log_error_write(lp_procedure_name, SQLERRM, COALESCE(lp_last_user, 'UNKNOWN'));
        RAISE;
END;
$proc$;

