-- ==============================================================
-- Script: 2_create_table.sql
-- Purpose: Create core application tables for a single tenant
-- Scope:   Single tenant
--
-- Run as:  tenant_<tenantID>_user
-- Target:  Database: dlmo_tenant_<tenantID>_db
--
-- Order:   2 - After 1_init_tenant_db.sql, before 3_create_view.sql
--
-- Version: 1.0.0
-- Last updated: 2025-01-15
-- Notes:
--   - Creates tables primarily in schema application_data
--   - Must be executed before views, functions, and audit scripts
-- ==============================================================

-- application_data.lk_kpi_category definition

-- Drop table

-- DROP TABLE application_data.lk_kpi_category;

CREATE TABLE IF NOT EXISTS application_data.lk_kpi_category (
	kpi_category_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	kpi_category_code varchar(70) NOT NULL,
	kpi_category_ds varchar(255) NULL,
	kpi_category_sort int4 NOT NULL,
	plant_id int8 NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	kpi_category_icon varchar NULL,
	CONSTRAINT pk_kpi_lk_category PRIMARY KEY (plant_id, kpi_category_id),
	CONSTRAINT uk_kpi_lk_category UNIQUE (kpi_category_code, plant_id)
);




-- application_data.lk_kpi_type definition

-- Drop table

-- DROP TABLE application_data.lk_kpi_type;

CREATE TABLE IF NOT EXISTS application_data.lk_kpi_type (
	kpi_type_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 101 MAXVALUE 9223372036854775807 START 101 CACHE 1 NO CYCLE) NOT NULL,
	kpi_type_code varchar(100) NULL,
	kpi_type_ds varchar(500) NULL,
	kpi_type_sort int4 NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	is_system_value bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_kpi_type PRIMARY KEY (kpi_type_id),
	CONSTRAINT uk_lk_kpi_type UNIQUE (kpi_type_code)
);



-- application_data.lk_kpi_uom definition

-- Drop table

-- DROP TABLE application_data.lk_kpi_uom;

CREATE TABLE IF NOT EXISTS application_data.lk_kpi_uom (
	kpi_uom_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 101 MAXVALUE 9223372036854775807 START 101 CACHE 1 NO CYCLE) NOT NULL,
	kpi_uom_code varchar(100) NULL,
	kpi_uom_ds varchar(500) NULL,
	kpi_uom_sort int4 NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	is_system_value bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_kpi_uom PRIMARY KEY (kpi_uom_id),
	CONSTRAINT uk_lk_kpi_uom UNIQUE (kpi_uom_code)
);



-- application_data.lk_kpi definition

-- Drop table

-- DROP TABLE application_data.lk_kpi;

CREATE TABLE IF NOT EXISTS application_data.lk_kpi (
	kpi_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	kpi_code varchar(100) NOT NULL,
	kpi_ds varchar(500) NULL,
	plant_id int8 NOT NULL,
	kpi_group_id int8 NOT NULL,
	kpi_category_id int8 NOT NULL,
	aggregation_rule_id int8 NOT NULL,
	kpi_uom_id int8 NOT NULL,
	kpi_sort int4 NULL,
	color_up_target_cd varchar(100) NULL,
	color_down_target_cd varchar(100) NULL,
	def_value numeric(20, 5) NULL,
	def_target numeric(20, 5) NULL,
	is_zero_display int4 DEFAULT 1 NOT NULL,
	is_automatic_value int4 DEFAULT 0 NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	target_tendency_id int4 NULL,
	kpi_type_id int8 NULL,
	is_main_kpi bool DEFAULT false NULL,
	CONSTRAINT pk_lk_kpi PRIMARY KEY (plant_id, kpi_id),
	CONSTRAINT uk_lk_kpi UNIQUE (plant_id, kpi_code)
);



-- application_data.lk_kpi_group definition

-- Drop table

-- DROP TABLE application_data.lk_kpi_group;

CREATE TABLE IF NOT EXISTS application_data.lk_kpi_group (
	kpi_group_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	kpi_group_code varchar(100) NOT NULL,
	kpi_group_ds varchar(500) NULL,
	kpi_group_sort int4 NOT NULL,
	plant_id int8 NOT NULL,
	kpi_category_id int8 NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_kpi_group_pkey PRIMARY KEY (plant_id, kpi_group_id, kpi_category_id),
	CONSTRAINT uk_lk_kpi_group UNIQUE (plant_id, kpi_category_id, kpi_group_code)
);




-- application_data.lk_action_priority definition

-- Drop table

-- DROP TABLE application_data.lk_action_priority;

CREATE TABLE IF NOT EXISTS application_data.lk_action_priority (
	action_priority_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	action_priority_cd varchar(100) NULL,
	action_priority_ds varchar(255) NULL,
	action_priority_sort int4 NULL,
	action_priority_icon varchar(255) NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	action_color_coding varchar NULL,
	priority_icon_kanban varchar NULL,
	CONSTRAINT pk_lk_action_priority PRIMARY KEY (action_priority_id),
	CONSTRAINT uq_lk_action_priority UNIQUE (action_priority_cd)
);



-- application_data.lk_action_status definition

-- Drop table

-- DROP TABLE application_data.lk_action_status;

CREATE TABLE IF NOT EXISTS application_data.lk_action_status (
	action_status_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	action_status_cd varchar(70) NULL,
	action_status_ds varchar(255) NULL,
	action_status_sort int4 NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_action_status PRIMARY KEY (action_status_id),
	CONSTRAINT uq_lk_action_status UNIQUE (action_status_cd)
);



-- application_data.lk_action definition

-- Drop table

-- DROP TABLE application_data.lk_action;

CREATE TABLE IF NOT EXISTS application_data.lk_action (
	plant_id int8 NOT NULL,
	action_id int8 NOT NULL,
	action_cd varchar(100) NOT NULL,
	action_html_ds varchar(2000) NULL,
	action_ds text NULL,
	module_id int8 NULL,
	line_id int8 NOT NULL,
	action_priority_id int8 NOT NULL,
	action_status_id int8 NOT NULL,
	kpi_category_id int8 NOT NULL,
	opening_tier_id int8 NOT NULL,
	assign_tier_id int8 NOT NULL,
	action_owner varchar NULL,
	action_raiser varchar NOT NULL,
	opening_day_local_id int4 NULL,
	opening_local_ts timestamp NULL,
	opening_utc_ts timestamp NULL,
	closure_day_local_id int4 NULL,
	closure_local_ts timestamp NULL,
	closure_utc_ts timestamp NULL,
	due_date_day_local_id int4 NULL,
	due_date_local_ts timestamp NULL,
	due_date_utc_ts timestamp NULL,
	owner_closure_day_local_id int4 NULL,
	owner_closure_local_ts timestamp NULL,
	owner_closure_utc_ts timestamp NULL,
	creation_day_local_id int4 NOT NULL,
	creation_local_ts timestamp NOT NULL,
	creation_utc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified_utc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_modified_local_day_id int4 NULL,
	last_modified_local_ts timestamp NULL,
	last_user varchar NOT NULL,
	is_escalated bool DEFAULT false NULL,
	is_no_escalation bool DEFAULT false NULL,
	is_on_time bool NULL,
	is_on_hold bool NULL,
	is_top_action bool NULL,
	meeting_id text NULL,
	CONSTRAINT pk_lk_actions PRIMARY KEY (plant_id, action_id),
	CONSTRAINT uq_lk_actions UNIQUE (plant_id, action_cd)
);
CREATE INDEX IF NOT EXISTS idx_lk_actions ON application_data.lk_action USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_1 ON application_data.lk_action USING btree (line_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_10 ON application_data.lk_action USING btree (due_date_day_local_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_12 ON application_data.lk_action USING btree (owner_closure_day_local_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_13 ON application_data.lk_action USING btree (is_top_action);
CREATE INDEX IF NOT EXISTS idx_lk_actions_14 ON application_data.lk_action USING btree (is_escalated);
CREATE INDEX IF NOT EXISTS idx_lk_actions_15 ON application_data.lk_action USING btree (plant_id, module_id, line_id, kpi_category_id, action_id, action_status_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_16 ON application_data.lk_action USING btree (is_no_escalation);
CREATE INDEX IF NOT EXISTS idx_lk_actions_17 ON application_data.lk_action USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_18 ON application_data.lk_action USING btree (action_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_19 ON application_data.lk_action USING btree (action_cd);
CREATE INDEX IF NOT EXISTS idx_lk_actions_20 ON application_data.lk_action USING btree (opening_tier_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_21 ON application_data.lk_action USING btree (assign_tier_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_3 ON application_data.lk_action USING btree (action_priority_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_4 ON application_data.lk_action USING btree (action_status_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_5 ON application_data.lk_action USING btree (kpi_category_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_6 ON application_data.lk_action USING btree (opening_tier_id);
CREATE INDEX IF NOT EXISTS idx_lk_actions_7 ON application_data.lk_action USING btree (action_owner);
CREATE INDEX IF NOT EXISTS idx_lk_actions_8 ON application_data.lk_action USING btree (action_raiser);
CREATE INDEX IF NOT EXISTS idx_lk_actions_9 ON application_data.lk_action USING btree (opening_day_local_id);



-- application_data.lk_action_files definition

-- Drop table

-- DROP TABLE application_data.lk_action_files;

CREATE TABLE IF NOT EXISTS application_data.lk_action_files (
	plant_id int8 NOT NULL,
	file_id numeric(18) NOT NULL,
	file_name varchar NOT NULL,
	file_size varchar NOT NULL,
	mimetype varchar NOT NULL,
	relativeurl varchar NOT NULL,
	action_id int8 NOT NULL,
	user_fullname varchar NULL,
	upload_timestamp timestamp NULL,
	is_deleted bool DEFAULT false NULL,
	CONSTRAINT lk_action_files_pkey PRIMARY KEY (plant_id, file_id),
	CONSTRAINT lk_action_files_unique UNIQUE (file_id)
);

-- application_data.lk_issue_status definition

-- Drop table

-- DROP TABLE application_data.lk_issue_status;

CREATE TABLE IF NOT EXISTS application_data.lk_issue_status (
	issue_status_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	issue_status_cd varchar(70) NULL,
	issue_status_ds varchar(255) NULL,
	issue_status_sort int4,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_issue_status PRIMARY KEY (issue_status_id),
	CONSTRAINT uq_lk_issue_status UNIQUE (issue_status_cd)
);



-- application_data.lk_issue definition

-- Drop table

-- DROP TABLE application_data.lk_issue;

CREATE TABLE IF NOT EXISTS application_data.lk_issue (
	plant_id int8 NOT NULL,
	module_id int8 NOT NULL,
	line_id int8 NOT NULL,
	issue_id int8 NOT NULL,
	issue_cd varchar(100) NOT NULL,
	issue_sh_ds varchar(500) NULL,
	issue_ds text NULL,
	kpi_category_id int8 NOT NULL,
	opening_tier_id int8 NOT NULL,
	start_day_local_id int4 NOT NULL,
	start_local_ts timestamp NOT NULL,
	start_utc_ts timestamp NOT NULL,
	end_day_local_id int4 NULL,
	end_local_ts timestamp NULL,
	end_utc_ts timestamp NULL,
	comment_ds text NULL,
	creation_day_local_id int4 NOT NULL,
	creation_local_ts timestamp NOT NULL,
	creation_utc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified_utc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_modified_local_day_id int4 NULL,
	last_modified_local_ts timestamp NULL,
	last_user varchar NOT NULL,
	shift_id int8 NULL,
	issue_priority_id int8 NULL,
	issue_status_id int8 NULL,
	CONSTRAINT pk_lk_issue PRIMARY KEY (plant_id, issue_id),
	CONSTRAINT uq_lk_issue UNIQUE (plant_id, issue_cd)
);


-- application_data.lk_issue_files definition

-- Drop table

-- DROP TABLE application_data.lk_issue_files;

CREATE TABLE IF NOT EXISTS application_data.lk_issue_files (
	plant_id int8 NOT NULL,
	file_id numeric(18) NOT NULL,
	file_name varchar NOT NULL,
	file_size varchar NOT NULL,
	mimetype varchar NOT NULL,
	relativeurl varchar NOT NULL,
	issue_id int8 NOT NULL,
	user_fullname varchar NULL,
	upload_timestamp timestamp NULL,
	is_deleted bool DEFAULT false NULL,
	CONSTRAINT lk_issue_files_pkey PRIMARY KEY (plant_id, file_id),
	CONSTRAINT uq_lk_issue_files UNIQUE (file_id)
);


-- application_data.lk_files definition

-- Drop table

-- DROP TABLE application_data.lk_files;

CREATE TABLE IF NOT EXISTS application_data.lk_files (
	id numeric(18) NOT NULL,
	plant_id int8 not null,
	"name" varchar NOT NULL,
	"size" varchar NOT NULL,
	mimetype varchar NOT NULL,
	relativeurl varchar NOT NULL,
	is_processed bool NULL,
	processed_timestamp timestamp NULL,
	username varchar NULL,
	upload_timestamp timestamp NULL,
	is_deleted bool DEFAULT false NULL,
	source varchar null,
	note varchar NULL,
	CONSTRAINT lk_files_pkey PRIMARY KEY (id)
);


-- application_data.lk_plant definition

-- Drop table

-- DROP TABLE application_data.lk_plant;

CREATE TABLE IF NOT EXISTS application_data.lk_plant (
	plant_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	plant_code varchar(100) NULL,
	plant_ds varchar(100) NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	is_editable bool DEFAULT true NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	company_id int8 NULL,
	latitude numeric(18, 6) NULL,
	longitude numeric(18, 6) NULL,
	plant_timezone varchar NOT NULL,
	organization_id numeric(16) NULL,
	CONSTRAINT pk_lk_plant PRIMARY KEY (plant_id),
	CONSTRAINT uq_lk_plant UNIQUE (plant_code)
);



-- application_data.lk_module definition

-- Drop table

-- DROP TABLE application_data.lk_module;

CREATE TABLE IF NOT EXISTS application_data.lk_module (
	module_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	module_code varchar(100) NULL,
	module_ds varchar(100) NOT NULL,
	plant_id int8 NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	is_editable bool DEFAULT true NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_module PRIMARY KEY (plant_id, module_id),
	CONSTRAINT uq_lk_module UNIQUE (plant_id, module_code)
);



-- application_data.lk_line definition

-- Drop table

-- DROP TABLE application_data.lk_line;

CREATE TABLE IF NOT EXISTS application_data.lk_line (
	line_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	line_code varchar(100) NULL,
	line_code_erp varchar(255) NOT NULL,
	process_key varchar(200) NULL,
	line_ds varchar(100) NOT NULL,
	plant_id int8 NOT NULL,
	module_id int8 NOT NULL,
	image_ref varchar(255) NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	is_editable bool DEFAULT true NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT lk_line_unique UNIQUE (plant_id, line_code),
	CONSTRAINT pk_lk_line PRIMARY KEY (plant_id, line_id)
);
CREATE INDEX IF NOT EXISTS fki_fk_lk_line_lk_module ON application_data.lk_line USING btree (plant_id, module_id);


-- application_data.lk_threshold definition (plant, line, kpi, validity interval)
-- DROP TABLE application_data.lk_threshold;
CREATE TABLE IF NOT EXISTS application_data.lk_threshold (
	threshold_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	kpi_id int8 NOT NULL,
	threshold_value numeric(18, 6) NOT NULL,
	start_date_local timestamp NOT NULL,
	start_date_utc timestamp NOT NULL,
	end_date_local timestamp NULL,
	end_date_utc timestamp NULL,
	start_date_id numeric(8) NOT NULL,
	end_date_id numeric(8) NULL,
	is_active bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_threshold PRIMARY KEY (plant_id, line_id, threshold_id),
	CONSTRAINT uq_lk_threshold UNIQUE (plant_id, line_id, kpi_id, start_date_local),
	CONSTRAINT fk_lk_threshold_lk_kpi FOREIGN KEY (plant_id, kpi_id) REFERENCES application_data.lk_kpi(plant_id, kpi_id),
	CONSTRAINT fk_lk_threshold_lk_line FOREIGN KEY (plant_id, line_id) REFERENCES application_data.lk_line(plant_id, line_id)
);

-- Indexes (for new install; existing DB without kpi_id use deploy_lk_threshold migration)
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'application_data' AND table_name = 'lk_threshold' AND column_name = 'kpi_id') THEN
        DROP INDEX IF EXISTS application_data.lk_threshold_one_open_uidx;
        CREATE UNIQUE INDEX IF NOT EXISTS lk_threshold_one_open_uidx
            ON application_data.lk_threshold (plant_id, line_id, kpi_id)
            WHERE is_deleted = false AND is_active = true AND end_date_local IS NULL;
        CREATE INDEX IF NOT EXISTS lk_threshold_plant_line_kpi_idx ON application_data.lk_threshold (plant_id, line_id, kpi_id);
        CREATE INDEX IF NOT EXISTS lk_threshold_validity_idx ON application_data.lk_threshold (plant_id, line_id, kpi_id, start_date_id, end_date_id);
    END IF;
END $$;

-- application_data.lk_target definition (KPI target per plant, line, kpi with validity interval; intervals must not overlap)
-- DROP TABLE application_data.lk_target;
CREATE TABLE IF NOT EXISTS application_data.lk_target (
	target_id int8 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	kpi_id int8 NOT NULL,
	target_value_num numeric(18, 6) NOT NULL,
	start_date_local timestamp NOT NULL,
	start_date_utc timestamp NOT NULL,
	end_date_local timestamp NULL,
	end_date_utc timestamp NULL,
	start_date_id numeric(8) NOT NULL,
	end_date_id numeric(8) NULL,
	is_active bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, current_timestamp) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, current_timestamp) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_target PRIMARY KEY (target_id),
	CONSTRAINT fk_lk_target_lk_kpi FOREIGN KEY (plant_id, kpi_id) REFERENCES application_data.lk_kpi(plant_id, kpi_id),
	CONSTRAINT fk_lk_target_lk_line FOREIGN KEY (plant_id, line_id) REFERENCES application_data.lk_line(plant_id, line_id)
);
COMMENT ON TABLE application_data.lk_target IS 'KPI target per plant, line, kpi with validity interval (start_date_id - end_date_id). Intervals must not overlap.';
CREATE INDEX IF NOT EXISTS lk_target_plant_line_kpi_idx ON application_data.lk_target (plant_id, line_id, kpi_id);
CREATE INDEX IF NOT EXISTS lk_target_validity_idx ON application_data.lk_target (plant_id, line_id, kpi_id, start_date_id, end_date_id);

-- application_data.lk_machine definition

-- Drop table

-- DROP TABLE application_data.lk_machine;

CREATE TABLE IF NOT EXISTS application_data.lk_machine (
	machine_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	machine_code varchar(100) NULL,
	machine_ds varchar(100) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	image_ref varchar(255) NULL,
	is_line_driver bool NULL,
	machine_type_id int8 NULL,
	is_active bool DEFAULT true NULL,
	fpy_active bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	machine_sort int2 NULL,
	source_id int8 NULL,
	is_start_step bool DEFAULT false NULL,
	is_end_step bool DEFAULT false NULL,
	CONSTRAINT lk_machine_pk PRIMARY KEY (machine_id, plant_id),
	CONSTRAINT lk_machine_unique UNIQUE (machine_id, line_id),
	CONSTRAINT lk_machine_unique_code UNIQUE (line_id, machine_code)
);

-- application_data.lk_machine_target definition
-- Machine-level target values with validity interval (used by manage_target/populate logic).
CREATE TABLE IF NOT EXISTS application_data.lk_machine_target (
	machine_target_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START 10 CACHE 1 NO CYCLE) NOT NULL,
	machine_id int8 NOT NULL,
	line_id int8 NOT NULL,
	plant_id int8 NOT NULL,
	target_value numeric(18, 6) NOT NULL,
	start_date_local timestamp NOT NULL,
	start_date_utc timestamp NOT NULL,
	end_date_local timestamp NULL,
	end_date_utc timestamp NULL,
	start_date_id numeric(8) NOT NULL,
	end_date_id numeric(8) NULL,
	is_active bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'::text) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'::text) NOT NULL,
	last_user varchar NOT NULL,
	is_processed bool DEFAULT false NULL,
	target_weight numeric(18, 6) DEFAULT 1 NULL,
	kpi_id int8 NULL,
	CONSTRAINT pk_lk_machine_target PRIMARY KEY (machine_target_id),
	CONSTRAINT lk_machine_target_unique UNIQUE (machine_id, line_id, plant_id, kpi_id, start_date_local),
	CONSTRAINT fk_lk_machine_target_lk_line FOREIGN KEY (plant_id, line_id) REFERENCES application_data.lk_line(plant_id, line_id),
	CONSTRAINT fk_lk_machine_target_lk_machine FOREIGN KEY (machine_id, plant_id) REFERENCES application_data.lk_machine(machine_id, plant_id)
);



-- application_data.lk_component definition

-- Drop table

-- DROP TABLE application_data.lk_component;

CREATE TABLE IF NOT EXISTS application_data.lk_component (
	component_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	component_code varchar(100) NULL,
	component_ds varchar(100) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NULL,
	machine_id int8 NOT NULL,
	image_ref varchar(255) NULL,
	component_type_id int8 NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_component PRIMARY KEY (component_id),
	CONSTRAINT lk_component_unique UNIQUE (component_code,machine_id)
);
CREATE INDEX IF NOT EXISTS lk_component_component_code_idx ON application_data.lk_component USING btree (component_code);
CREATE INDEX IF NOT EXISTS lk_component_plant_id_idx ON application_data.lk_component USING btree (plant_id, line_id, component_id);


-- application_data.lk_frequency definition

-- Drop table

-- DROP TABLE application_data.lk_frequency;

CREATE TABLE IF NOT EXISTS application_data.lk_frequency (
	frequency_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	frequency_code varchar(50) NOT NULL,
	frequency_ds varchar(50) NOT NULL,
	is_active bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT lk_frequency_frequencyds_key UNIQUE (frequency_ds),
	CONSTRAINT pk_lk_frequency PRIMARY KEY (frequency_id),
	CONSTRAINT uq_lk_frequency UNIQUE (frequency_code)
);



-- application_data.lk_external_link definition

-- Drop table

-- DROP TABLE application_data.lk_external_link;

CREATE TABLE IF NOT EXISTS application_data.lk_external_link (
	url_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	tier_id int8 NOT NULL,
	url_code text NOT NULL,
	url_sh_ds varchar(500) NOT NULL,
	url_ds text NULL,
	is_active bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_external_link PRIMARY KEY (plant_id, tier_id, url_id),
	CONSTRAINT uq_lk_external_link UNIQUE (plant_id, tier_id, url_code, url_sh_ds)
);



-- application_data.lk_tier definition

-- Drop table

-- DROP TABLE application_data.lk_tier;

CREATE TABLE IF NOT EXISTS application_data.lk_tier (
	tier_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	tier_code varchar(100) NULL,
	tier_ds varchar(100) NOT NULL,
	plant_id int8 NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	is_editable bool DEFAULT true NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	tier_sort int8 NOT NULL,
	frequency_id int8 NOT NULL,
	tier_meeting_color varchar NULL,
	CONSTRAINT pk_lk_tier PRIMARY KEY (plant_id, tier_id),
	CONSTRAINT uq_lk_tier UNIQUE (plant_id, tier_code)
);


-- application_data.lk_timezone definition

-- Drop table

-- DROP TABLE application_data.lk_timezone;

CREATE TABLE IF NOT EXISTS application_data.lk_timezone (
	timezone_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	timezone_cd varchar(100) NOT NULL,
	timezone_ds varchar(500) NULL,
	utc_offset varchar(100) NULL,
	utc_dst_offset varchar(100) NULL,
	creation_ts timestamp(0) DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar(255) NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	is_editable bool DEFAULT false NOT NULL,
	last_modified timestamp(0) DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_timezone PRIMARY KEY (timezone_id),
	CONSTRAINT uniq_lk_timezone UNIQUE (timezone_cd)
);
CREATE INDEX IF NOT EXISTS idx_lk_timezone ON application_data.lk_timezone USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_lk_timezone_1 ON application_data.lk_timezone USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS idx_lk_timezone_2 ON application_data.lk_timezone USING btree (is_editable);


-- application_data.lk_aggregation_rule definition

-- Drop table

-- DROP TABLE application_data.lk_aggregation_rule;

CREATE TABLE IF NOT EXISTS application_data.lk_aggregation_rule (
	aggregation_rule_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	aggregation_rule_code varchar(100) NOT NULL,
	aggregation_rule_ds varchar(500) NULL,
	aggregation_rule_sort int4 NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	is_system_value bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pklk_aggregation_role PRIMARY KEY (aggregation_rule_id),
	CONSTRAINT uklk_aggregation_role UNIQUE (aggregation_rule_code)
);


-- application_data.lk_attendance_status definition

-- Drop table

-- DROP TABLE application_data.lk_attendance_status;

CREATE TABLE IF NOT EXISTS application_data.lk_attendance_status (
	at_status_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	at_status_code varchar(100) NULL,
	at_status_ds varchar(500) NULL,
	at_status_sort int4 NULL,
	at_status_color varchar(100) NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_attendance_status PRIMARY KEY (at_status_id),
	CONSTRAINT uk_lk_attendance_status UNIQUE (at_status_code)
);



-- application_data.lk_attendance_role definition

-- Drop table

-- DROP TABLE application_data.lk_attendance_role;

CREATE TABLE IF NOT EXISTS application_data.lk_attendance_role (
	attendance_role_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	attendance_role_code varchar(100) NOT NULL,
	attendance_role_ds varchar(500) NULL,
	plant_id int8 NOT NULL,
	is_modify bool DEFAULT true NOT NULL,
	is_active bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_attendance_role PRIMARY KEY (plant_id, attendance_role_id),
	CONSTRAINT uk_lk_attendance_role UNIQUE (plant_id, attendance_role_code)
);


-- application_data.ass_module_line_tier_kpi definition

-- Drop table

-- DROP TABLE application_data.ass_module_line_tier_kpi;

CREATE TABLE IF NOT EXISTS application_data.ass_module_line_tier_kpi (
	amltk_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	kpi_id int8 NOT NULL,
	tier_id int8 NOT NULL,
	line_id int8 NOT NULL,
	module_id int8 NOT NULL,
	plant_id int8 NOT NULL,
	is_active bool DEFAULT true NULL,
	is_deleted bool DEFAULT false NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_ass_module_line_tier_kpi PRIMARY KEY (amltk_id),
	CONSTRAINT uk_pk_ass_module_line_tier_kpi UNIQUE (kpi_id, tier_id, line_id, module_id, plant_id)
);

-- application_data.ft_attendance definition

-- Drop table

-- DROP TABLE application_data.ft_attendance;

CREATE TABLE IF NOT EXISTS application_data.ft_attendance (
	plant_id int8 NOT NULL,
	tier_id int8 NOT NULL,
	module_id int8 NOT NULL,
	line_id int8 NOT NULL,
	day_id int4 NOT NULL,
	attendance_role_id int4 NOT NULL,
	status_id int8 NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_ft_attendance PRIMARY KEY (plant_id, tier_id, module_id, line_id, day_id, attendance_role_id)
)
PARTITION BY LIST (plant_id);
CREATE INDEX IF NOT EXISTS idx_ft_attendance ON ONLY application_data.ft_attendance USING btree (status_id);


-- application_data.ft_kpi_target definition

-- DROP TABLE application_data.ft_kpi_target;

CREATE TABLE IF NOT EXISTS application_data.ft_kpi_target (
	target_id int8 NULL,
	kpi_id int8 NULL,
	tier_id int8 NULL,
	line_id int8 NULL,
	module_id int8 NULL,
	plant_id int8 NOT NULL,
	kpi_category_id int8 NULL,
	target_tendency_id int8 NULL,
	target_date date NULL,
	target_date_iso numeric(8) NOT NULL,
	frequency_id int8 NULL,
	frequency_ds varchar(50) NULL,
	target_value varchar NULL,
	target_value_num numeric(18, 6) NULL,
	kpi_value numeric(18, 6) NULL,
	is_visible bool NULL,
	is_editable bool NULL,
	creation_ts timestamp NULL,
	creator_user varchar NULL,
	last_modified timestamp NULL,
	last_user varchar NULL,
	good_value numeric(18, 6) NULL,
	total_good numeric(18, 6) NULL,
	total_delivery int8 NULL,
	on_time_delivery int8 NULL,
	import_id int8 NULL,
	CONSTRAINT ft_kpi_target_unique UNIQUE (kpi_id, tier_id, line_id, module_id, plant_id, target_date_iso)
)
PARTITION BY LIST (plant_id);
CREATE INDEX IF NOT EXISTS ft_kpi_target_target_date_iso_idx ON ONLY application_data.ft_kpi_target USING btree (target_date_iso);

-- application_data.ft_quality definition
-- Support table for FPY calculation (good/total first pass) at day + component/fixture/shift level.
CREATE TABLE IF NOT EXISTS application_data.ft_quality (
	quality_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	day_id numeric(8) NOT NULL,
	production_date date NOT NULL,
	shift_dwh_id int8 NOT NULL,
	code_id int8 NULL,
	machine_id int8 NOT NULL,
	component_id int8 NULL,
	fixture_id int8 NOT NULL,
	good_first_pass int8 NOT NULL,
	total_first_pass int8 NOT NULL,
	calc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	calc_caller varchar(255) NULL,
	CONSTRAINT pk_ft_quality PRIMARY KEY (quality_id, plant_id, day_id)
)
PARTITION BY LIST (plant_id);

CREATE UNIQUE INDEX IF NOT EXISTS ft_quality_uidx ON application_data.ft_quality (plant_id, line_id, day_id, shift_dwh_id, COALESCE(code_id, -1), machine_id, COALESCE(component_id, -1), fixture_id);
CREATE INDEX IF NOT EXISTS ft_quality_day_idx ON ONLY application_data.ft_quality USING btree (day_id);
CREATE INDEX IF NOT EXISTS ft_quality_plant_line_idx ON ONLY application_data.ft_quality USING btree (plant_id, line_id);

-- application_data.ft_oee_shift definition
-- Support table for OEE component metrics at day + shift + step + machine + component level.
CREATE TABLE IF NOT EXISTS application_data.ft_oee_shift (
	oee_shift_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	day_id numeric(8) NOT NULL,
	production_date date NOT NULL,
	shift_dwh_id int8 NOT NULL,
	source_step_id int4 NOT NULL,
	machine_id int8 NOT NULL,
	component_id int8 NULL,
	ideal_cycle_time_ms int4 NULL,
	parallel_component_count_step int4 NULL,
	effective_step_cycle_time_ms numeric(18, 3) NULL,
	shift_working_duration_sec numeric(20, 5) NOT NULL,
	good_first_pass int8 NOT NULL,
	total_pcs int8 NOT NULL,
	ideal_production_machine numeric(18, 3) NULL,
	ideal_production_step numeric(18, 3) NULL,
	oee_component numeric(18, 6) NULL,
	calc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	calc_caller varchar(255) NULL,
	CONSTRAINT pk_ft_oee_shift PRIMARY KEY (oee_shift_id, plant_id, day_id)
)
PARTITION BY LIST (plant_id);

CREATE UNIQUE INDEX IF NOT EXISTS ft_oee_shift_uidx
ON application_data.ft_oee_shift (
	plant_id, line_id, day_id, shift_dwh_id, source_step_id, machine_id, COALESCE(component_id, -1)
);
CREATE INDEX IF NOT EXISTS ft_oee_shift_day_idx ON ONLY application_data.ft_oee_shift USING btree (day_id);
CREATE INDEX IF NOT EXISTS ft_oee_shift_plant_line_idx ON ONLY application_data.ft_oee_shift USING btree (plant_id, line_id);

-- application_data.ft_oee definition
-- Daily OEE support table at step + machine + component level; includes line-level denominator/numerator components.
CREATE TABLE IF NOT EXISTS application_data.ft_oee (
	oee_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	day_id numeric(8) NOT NULL,
	production_date date NOT NULL,
	shift_count int4 NOT NULL,
	observed_duration_sec numeric(20, 5) NOT NULL,
	source_step_id int4 NOT NULL,
	machine_id int8 NOT NULL,
	machine_code varchar(100) NULL,
	component_id int8 NULL,
	component_code varchar(100) NULL,
	is_end_step bool DEFAULT false NOT NULL,
	parallel_component_count_step int4 NULL,
	ideal_cycle_time_ms int4 NULL,
	effective_step_cycle_time_ms numeric(18, 3) NULL,
	good_first_pass int8 NOT NULL,
	total_pcs int8 NOT NULL,
	ideal_production_machine numeric(18, 3) NULL,
	ideal_production_step numeric(18, 3) NULL,
	oee_component numeric(18, 6) NULL,
	line_output_good int8 NULL,
	line_capacity_ideal numeric(18, 3) NULL,
	is_bottleneck_step bool DEFAULT false NOT NULL,
	calc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	calc_caller varchar(255) NULL,
	CONSTRAINT pk_ft_oee PRIMARY KEY (oee_id, plant_id, day_id)
)
PARTITION BY LIST (plant_id);

CREATE UNIQUE INDEX IF NOT EXISTS ft_oee_uidx
ON application_data.ft_oee (
	plant_id, line_id, day_id, source_step_id, machine_id, COALESCE(component_id, -1)
);
CREATE INDEX IF NOT EXISTS ft_oee_day_idx ON ONLY application_data.ft_oee USING btree (day_id);
CREATE INDEX IF NOT EXISTS ft_oee_plant_line_idx ON ONLY application_data.ft_oee USING btree (plant_id, line_id);

-- application_data.ft_downtime definition
-- Origine: [sp203_an].[Downtime] (SQL Server). Caricata da application_staging.etl_sync_downtime.
-- Contiene riferimenti sorgente (*_IntId) e target (shift_dwh_id, code_id, component_id, day_id, plant_id, line_id).
-- DROP TABLE application_data.ft_downtime;
CREATE TABLE IF NOT EXISTS application_data.ft_downtime (
	downtime_id int8 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	-- Chiavi SORGENTE (tracciabilità DWH)
	source_downtime_id int4 NOT NULL,
	source_shift_id int4 NOT NULL,
	source_production_time_hal_hour_id int4 NOT NULL,
	source_production_time_date_id int4 NOT NULL,
	source_code_id int4 NULL,
	source_component_id int4 NOT NULL,
	-- Chiavi TARGET (FK lookup)
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	day_id numeric(8) NOT NULL,
	shift_dwh_id int8 NOT NULL,
	code_id int8 NULL,
	component_id int8 NOT NULL,
	-- Dati Downtime
	severity_en smallint NOT NULL,
	stream_en smallint NOT NULL,
	tool_name text NULL,
	description text NULL,
	datetime_start timestamp NOT NULL,
	datetime_end timestamp NOT NULL,
	interval_time_ms int4 NOT NULL,
	-- Audit ETL
	etl_batch_id varchar(50) NULL,
	etl_loaded_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	CONSTRAINT pk_ft_downtime PRIMARY KEY (downtime_id, plant_id, day_id),
	CONSTRAINT uk_ft_downtime_source UNIQUE (plant_id, day_id, source_downtime_id)
) PARTITION BY LIST (plant_id);
CREATE INDEX IF NOT EXISTS ft_downtime_day_idx ON ONLY application_data.ft_downtime USING btree (day_id);
CREATE INDEX IF NOT EXISTS ft_downtime_plant_line_idx ON ONLY application_data.ft_downtime USING btree (plant_id, line_id);
CREATE INDEX IF NOT EXISTS ft_downtime_shift_idx ON ONLY application_data.ft_downtime USING btree (shift_dwh_id);
CREATE INDEX IF NOT EXISTS ft_downtime_component_idx ON ONLY application_data.ft_downtime USING btree (component_id);
COMMENT ON TABLE application_data.ft_downtime IS 'Fact table downtime - origine: [sp203_an].[Downtime]. Sincronizzata da etl_sync_downtime.';

-- application_data.ft_safety_cross definition

-- Drop table

-- DROP TABLE application_data.ft_safety_cross;

CREATE TABLE IF NOT EXISTS application_data.ft_safety_cross (
	safety_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	module_id int8 NOT NULL,
	line_id int8 NOT NULL,
	safety_category_id int8 NOT NULL,
	safety_type_id int8 NOT NULL,
	day_id int4 NOT NULL,
	day_ts timestamp NOT NULL,
	comment_ds text NULL,
	num_day int4 DEFAULT 0 NULL,
	day_lost int4 NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	import_id numeric NULL,
	CONSTRAINT ft_safety_cross_pk PRIMARY KEY (safety_id, plant_id, day_id)
)
PARTITION BY LIST (plant_id);
CREATE INDEX IF NOT EXISTS idx_ft_safety_cross_catecory ON ONLY application_data.ft_safety_cross USING btree (safety_category_id);
CREATE INDEX IF NOT EXISTS idx_ft_safety_cross_day ON ONLY application_data.ft_safety_cross USING btree (day_id);
CREATE INDEX IF NOT EXISTS idx_ft_safety_cross_line ON ONLY application_data.ft_safety_cross USING btree (line_id);
CREATE INDEX IF NOT EXISTS idx_ft_safety_cross_module ON ONLY application_data.ft_safety_cross USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_ft_safety_cross_plant ON ONLY application_data.ft_safety_cross USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_ft_safety_cross_type ON ONLY application_data.ft_safety_cross USING btree (safety_type_id);


-- application_data.lk_offset definition

-- Drop table

-- DROP TABLE application_data.lk_offset;

CREATE TABLE IF NOT EXISTS application_data.lk_offset (
	offset_cd int4 NOT NULL,
	offset_ds varchar(255) NULL
);


-- application_data.lk_safety_category definition

-- Drop table

-- DROP TABLE application_data.lk_safety_category;

CREATE TABLE IF NOT EXISTS application_data.lk_safety_category (
	plant_id int8 NOT NULL,
	safety_category_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	safety_category_code varchar(100) NULL,
	safety_category_ds varchar(500) NULL,
	safety_category_sort int4 NOT NULL,
	is_active bool DEFAULT true NOT NULL,
	is_deleted bool DEFAULT false NOT NULL,
	is_modify bool DEFAULT true NOT NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_safety_category PRIMARY KEY (plant_id, safety_category_id),
	CONSTRAINT uq_lk_safety_category UNIQUE (plant_id, safety_category_code)
);
CREATE INDEX IF NOT EXISTS idx_lk_safety_category_0 ON application_data.lk_safety_category USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_lk_safety_category_1 ON application_data.lk_safety_category USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS idx_lk_safety_category_2 ON application_data.lk_safety_category USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_lk_safety_category_3 ON application_data.lk_safety_category USING btree (safety_category_id);
CREATE INDEX IF NOT EXISTS idx_lk_safety_category_4 ON application_data.lk_safety_category USING btree (safety_category_code);



-- application_data.lk_safety_type definition

-- Drop table

-- DROP TABLE application_data.lk_safety_type;

CREATE TABLE IF NOT EXISTS application_data.lk_safety_type (
	safety_type_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	safety_type_code varchar(100) NULL,
	safety_type_ds varchar(500) NULL,
	safety_sort int4 NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_safety_type PRIMARY KEY (safety_type_id),
	CONSTRAINT un_lk_safety_type UNIQUE (safety_type_code)
);
CREATE INDEX IF NOT EXISTS idx_sc_lk_safety_type ON application_data.lk_safety_type USING btree (safety_sort);



-- application_data.lk_target_tendency definition

-- Drop table

-- DROP TABLE application_data.lk_target_tendency;

CREATE TABLE IF NOT EXISTS application_data.lk_target_tendency (
	target_tendency_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	target_tendency_code int4 NULL,
	target_tendency_ds varchar(500) NULL,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	CONSTRAINT pk_lk_target_tendency PRIMARY KEY (target_tendency_id),
	CONSTRAINT uq_lk_target_tendency UNIQUE (target_tendency_code)
);


-- application_data.log_error definition

-- Drop table

-- DROP TABLE application_data.log_error;

CREATE TABLE IF NOT EXISTS application_data.log_error (
	error_ref int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	error_timestamp timestamp NOT NULL,
	error_src varchar(100) NOT NULL,
	error_msg varchar(2000) NOT NULL,
	error_caller varchar NULL,
	CONSTRAINT pk_log_error PRIMARY KEY (error_ref)
);

-- Configurazione per log_error_write: connection string per dblink (con password)
-- così la scrittura in log_error persiste anche da blocchi EXCEPTION.
-- Inserire una riga con config_key = 'dblink_conn_str' e config_value = conn string completo
-- (es. dbname=xxx user=xxx password=xxx host=... port=5432). Se assente, si usa dbname+user senza password.
-- DROP TABLE application_data.log_error_write_cfg;
CREATE TABLE IF NOT EXISTS application_data.log_error_write_cfg (
	config_key   varchar(100) NOT NULL,
	config_value text         NULL,
	CONSTRAINT pk_log_error_write_cfg PRIMARY KEY (config_key)
);


-- application_data.log_operation definition

-- Drop table

-- DROP TABLE application_data.log_operation;

CREATE TABLE IF NOT EXISTS application_data.log_operation (
	operation_ref int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	operation_timestamp timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	operation_src varchar(100) NOT NULL,
	operation_msg varchar(4000) NOT NULL,
	operation_caller varchar NOT NULL,
	CONSTRAINT pk_log_operation PRIMARY KEY (operation_ref)
);

-- application_staging.etl_log_error definition (ETL persistent errors)
CREATE TABLE IF NOT EXISTS application_staging.etl_log_error (
	error_ref int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	error_timestamp timestamp NOT NULL DEFAULT timezone('utc'::text, current_timestamp),
	error_src varchar(100) NOT NULL,
	error_msg varchar(2000) NOT NULL,
	error_caller varchar NULL,
	CONSTRAINT pk_etl_log_error PRIMARY KEY (error_ref)
);

-- application_staging.etl_log_operation definition (ETL operational logs)
CREATE TABLE IF NOT EXISTS application_staging.etl_log_operation (
	operation_ref int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	operation_timestamp timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	operation_src varchar(100) NOT NULL,
	operation_msg varchar(4000) NOT NULL,
	operation_caller varchar NOT NULL,
	CONSTRAINT pk_etl_log_operation PRIMARY KEY (operation_ref)
);

-- application_data.map_action_issue definition

-- Drop table

-- DROP TABLE application_data.map_action_issue;

CREATE TABLE IF NOT EXISTS application_data.map_action_issue (
	plant_id int8 NOT NULL,
	issue_id int8 NOT NULL,
	action_id int8 NOT NULL,
	creation_day_local_id int4 NOT NULL,
	creation_local_ts timestamp NOT NULL,
	creation_utc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	CONSTRAINT pk_map_action_issue PRIMARY KEY (plant_id, issue_id, action_id)
);
CREATE INDEX IF NOT EXISTS idx_map_action_issue ON application_data.map_action_issue USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_map_action_issue_0 ON application_data.map_action_issue USING btree (issue_id);
CREATE INDEX IF NOT EXISTS idx_map_action_issue_1 ON application_data.map_action_issue USING btree (action_id);


-- application_data.map_attendance_tier definition

-- Drop table

-- DROP TABLE application_data.map_attendance_tier;

CREATE TABLE IF NOT EXISTS application_data.map_attendance_tier (
	plant_id int8 NOT NULL,
	tier_id int8 NOT NULL,
	attendance_role_id int8 NOT NULL,
	is_active bool DEFAULT false NOT NULL,
	au_user_id int8 NULL,
	au_change_type varchar(10) NULL,
	au_change_num int8 NULL,
	au_change_day_id int4 NULL,
	au_change_ts timestamp NULL,
	is_assigned bool NULL,
	CONSTRAINT pk_map_attendance_tier PRIMARY KEY (plant_id, tier_id, attendance_role_id)
);
CREATE INDEX IF NOT EXISTS idx_map_attendance_tier ON application_data.map_attendance_tier USING btree (is_active);


-- application_data.talend_log definition

-- Drop table

-- DROP TABLE application_data.talend_log;

CREATE TABLE IF NOT EXISTS application_data.talend_log (
	moment timestamp NULL,
	pid varchar(20) NULL,
	root_pid varchar(20) NULL,
	father_pid varchar(20) NULL,
	project varchar(50) NULL,
	job varchar(255) NULL,
	context varchar(50) NULL,
	priority int4 NULL,
	"type" varchar(255) NULL,
	origin varchar(255) NULL,
	message text NULL,
	code int4 NULL
);
CREATE INDEX IF NOT EXISTS idx_talend_log ON application_data.talend_log USING btree (moment);


-- application_data.talend_stat definition

-- Drop table

-- DROP TABLE application_data.talend_stat;

CREATE TABLE IF NOT EXISTS application_data.talend_stat (
	moment timestamp NULL,
	pid varchar(20) NULL,
	father_pid varchar(20) NULL,
	root_pid varchar(20) NULL,
	system_pid int8 NULL,
	project varchar(50) NULL,
	job varchar(255) NULL,
	job_repository_id varchar(255) NULL,
	job_version varchar(255) NULL,
	context varchar(50) NULL,
	origin varchar(255) NULL,
	message_type varchar(255) NULL,
	message varchar(255) NULL,
	duration int8 NULL
);
CREATE INDEX IF NOT EXISTS idx_talend_stat ON application_data.talend_stat USING btree (moment);


-- application_data.lk_date definition

-- Drop table

-- DROP TABLE application_data.lk_date;

CREATE TABLE IF NOT EXISTS application_data.lk_date (
	id_day numeric(8) NOT NULL,
	dsl_day varchar(30) NULL,
	dss_day varchar(20) NULL,
	id_week numeric(6) NULL,
	dsl_week varchar(30) NULL,
	dss_week varchar(20) NULL,
	id_weekday numeric(1) NULL,
	id_month numeric(6) NULL,
	id_quarter numeric(6) NULL,
	id_year numeric(6) NULL,
	last_of_month numeric(1) NULL,
	last_of_year numeric(1) NULL,
	trans_prev numeric(8) NULL,
	trans_ldw numeric(8) NULL,
	trans_ly numeric(8) NULL,
	CONSTRAINT lk_date_pr_key PRIMARY KEY (id_day)
);


-- application_data.lk_month definition

-- Drop table

-- DROP TABLE application_data.lk_month;

CREATE TABLE IF NOT EXISTS application_data.lk_month (
	id_month numeric(6) NOT NULL,
	dsl_month varchar(30) NULL,
	dss_month varchar(20) NULL,
	id_month_of_year numeric(2) NULL,
	id_quarter numeric(6) NULL,
	id_year numeric(6) NULL,
	day_month numeric(3) NULL,
	wdays_month numeric(3) NULL,
	trans_prev numeric(6) NULL,
	trans_ly numeric(6) NULL,
	CONSTRAINT lk_month_pr_key PRIMARY KEY (id_month)
);

-- application_data.lk_quarter definition

-- Drop table

-- DROP TABLE application_data.lk_quarter;

CREATE TABLE IF NOT EXISTS application_data.lk_quarter (
	id_quarter numeric(6) NOT NULL,
	dsl_quarter varchar(30) NULL,
	dss_quarter varchar(20) NULL,
	id_year numeric(4) NULL,
	id_quarter_of_year numeric(1) NULL,
	wdays_quarter numeric(3) NULL,
	trans_prev numeric(6) NULL,
	trans_ly numeric(6) NULL,
	CONSTRAINT lk_quart_pr_key PRIMARY KEY (id_quarter)
);

-- application_data.lk_year definition

-- Drop table

-- DROP TABLE application_data.lk_year;

CREATE TABLE IF NOT EXISTS application_data.lk_year (
	id_year numeric(4) NOT NULL,
	dsl_year varchar(30) NULL,
	dss_year varchar(20) NULL,
	day_year numeric(3) NULL,
	wdays_year numeric(3) NULL,
	trans_ly numeric(4) NULL,
	trans_prev numeric(4) NULL,
	CONSTRAINT lk_year_pr_key PRIMARY KEY (id_year)
);


-- application_data.lk_week_day definition

-- Drop table

-- DROP TABLE application_data.lk_week_day;

CREATE TABLE IF NOT EXISTS application_data.lk_week_day (
	week_day_id int4 NOT NULL,
	week_day_desc varchar(255) NULL
);


-- application_data.ft_meeting definition

-- Drop table

-- DROP TABLE application_data.ft_meeting;

CREATE TABLE IF NOT EXISTS application_data.ft_meeting (
	plant_id int8 NOT NULL,
	tier_id int8 NOT NULL,
	line_id int8 NOT NULL,
	module_id int8 NOT NULL,
	day_id int4 NOT NULL,
	meeting_start_ts timestamp default null,
	meeting_end_ts timestamp default null,
	duation int8 default null,
	creation_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	last_modified timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NULL,
	last_user varchar NOT NULL,
	count_attendance int8 NOT NULL,
	original_meeting text NULL,
	meeting_format text NULL,
	note_id varchar NULL,
	meeting_title varchar NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	CONSTRAINT ft_meeting_unique UNIQUE (plant_id, tier_id, line_id, module_id, day_id, note_id)
)
PARTITION BY LIST (plant_id);
CREATE INDEX IF NOT EXISTS idx_ft_meeting ON ONLY application_data.ft_meeting USING btree (plant_id);


-- application_data.lk_root_cause definition

-- Drop table

-- DROP TABLE application_data.lk_root_cause;

CREATE TABLE IF NOT EXISTS application_data.lk_root_cause (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	tier_id int8 NOT NULL,
	line_id int8 NOT NULL,
	module_id int8 NOT NULL,
	issue text NULL,
	solution text NULL,
	creation_ts timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'::text) NULL,
	creator_user varchar NULL,
	last_modified timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'::text) NULL,
	last_user varchar NULL,
	solution_html text NULL,
	CONSTRAINT pk_lk_root_cause PRIMARY KEY (id)
);


-- DROP TABLE application_staging.ft_kpi_target;

CREATE TABLE IF NOT EXISTS application_staging.ft_kpi_target (
	import_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	kpi text NOT NULL,
	plant text NOT NULL,
	line text NOT NULL,
	tier text NOT NULL,
	"day" int4 NOT NULL,
	value numeric(10, 2) NOT NULL,
	target numeric(10, 2) NOT NULL,
	file_id varchar NOT NULL,
	upload_data timestamp NOT NULL,
	is_processed int4 DEFAULT 0 NULL,
	is_rejected int4 DEFAULT 0 NULL,
	note varchar NULL,
	has_unhandled_error bool DEFAULT false NULL,
	CONSTRAINT ft_kpi_target_pk PRIMARY KEY (import_id),
	CONSTRAINT unq_kpi_target UNIQUE (kpi, plant, line, tier, day, file_id)
);
CREATE INDEX IF NOT EXISTS ft_kpi_target_file_id_idx ON application_staging.ft_kpi_target USING btree (file_id);

-- application_data.ft_pareto_data definition

-- Drop table

CREATE TABLE IF NOT EXISTS application_data.ft_pareto_data (
	pareto_data_id int8 NULL,
	item varchar NULL,
	kpi_id int8 NULL,
	tier_id int8 NULL,
	line_id int8 NULL,
	module_id int8 NULL,
	plant_id int8 NOT NULL,
	kpi_category_id int8 NULL,
	day_id numeric(8) NOT NULL,
	"day" timestamp NULL,
	value numeric(18, 6) NULL,
	is_visible bool NULL,
	is_editable bool NULL,
	creation_ts timestamp NULL,
	creator_user varchar NULL,
	last_modified timestamp NULL,
	last_user varchar NULL,
	import_id int8 NULL,
	CONSTRAINT ft_pareto_data_unique UNIQUE (item, kpi_id, tier_id, line_id, module_id, plant_id, day_id)
)
PARTITION BY LIST (plant_id);


-- DROP TABLE application_staging.ft_pareto_data;

CREATE TABLE IF NOT EXISTS application_staging.ft_pareto_data (
	import_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	kpi text NOT NULL,
	plant text NOT NULL,
	line text NOT NULL,
	tier text NOT NULL,
	item text NOT NULL,
	"day" int4 NOT NULL,
	value numeric(10, 2) NOT NULL,
	file_id varchar NOT NULL,
	upload_data timestamp NOT NULL,
	is_processed int4 DEFAULT 0 NULL,
	is_rejected int4 DEFAULT 0 NULL,
	note varchar NULL,
	has_unhandled_error bool DEFAULT false NULL,
	CONSTRAINT ft_pareto_data_pk PRIMARY KEY (import_id)
);
CREATE INDEX IF NOT EXISTS ft_pareto_data_file_id_idx ON application_staging.ft_pareto_data USING btree (file_id);

-- DROP TABLE application_staging.ft_safety_cross;

CREATE TABLE IF NOT EXISTS application_staging.ft_safety_cross (
	import_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant text NOT NULL,
	line text NOT NULL,
	safety_category text NOT NULL,
	safety_type text NOT NULL,
	"day" int4 NOT NULL,
	event_datetime timestamp NOT NULL,
	day_lost numeric(10, 2) NULL,
	"comment" text NULL,
	file_id varchar NOT NULL,
	upload_data timestamp NOT NULL,
	is_processed int4 DEFAULT 0 NULL,
	is_rejected int4 DEFAULT 0 NULL,
	note varchar NULL,
	has_unhandled_error bool DEFAULT false NULL,
	CONSTRAINT ft_safety_cross_pk PRIMARY KEY (import_id)
);
CREATE INDEX IF NOT EXISTS ft_safety_cross_file_id_idx ON application_staging.ft_safety_cross USING btree (file_id);

-- application_staging.etl_monitoring: traccia avvio/fine e stato (running|success|failed|skipped) di application_staging.etl_run_all_lookups.
-- Date in UTC e in local (plant_timezone). Campi timestamp without time zone.
-- All'UPDATE a state='success' un trigger chiama application_data.populate_ft_quality_fpy.
-- DROP TABLE IF EXISTS application_staging.etl_monitoring;
CREATE TABLE IF NOT EXISTS application_staging.etl_monitoring (
	id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	procedure_name varchar(200) NOT NULL DEFAULT 'application_staging.etl_run_all_lookups',
	start_ts_utc   timestamp NULL,
	start_ts_local timestamp NULL,
	end_ts_utc     timestamp NULL,
	end_ts_local   timestamp NULL,
	state          varchar(20) NOT NULL CHECK (state IN ('running', 'success', 'failed', 'skipped')),
	error_msg      text NULL,
	date_min       date NULL,
	date_max       date NULL,
	plant_id       bigint NULL
);
COMMENT ON TABLE application_staging.etl_monitoring IS 'Semaforo ETL: avvio/fine e stato di etl_run_all_lookups (running|success|failed|skipped). skipped=nessuno schema processato; trigger su success esegue populate_ft_quality_fpy e populate_ft_oee. UTC e local (plant). date_min/date_max e plant_id.';


-- application_data.lk_pending_actions definition

-- Drop table

-- DROP TABLE application_data.lk_pending_actions;

CREATE TABLE IF NOT EXISTS application_data.lk_pending_actions (
	meeting_cd varchar NULL,
	meeting_id varchar NOT NULL,
	meeting_date timestamp NULL,
	plant_id int8 NOT NULL,
	action_id int8 NOT NULL,
	action_cd varchar(100) NOT NULL,
	action_html_ds varchar(2000) NULL,
	action_ds text NULL,
	module_id int8 NULL,
	line_id int8 NOT NULL,
	action_priority_id int8 NOT NULL,
	action_status_id int8 NOT NULL,
	is_processed int4 DEFAULT 0 NULL,
	raice_notice text NULL,
	kpi_category_id int8 NULL,
	opening_tier_id int8 NOT NULL,
	assign_tier_id int8 NOT NULL,
	action_owner varchar NULL,
	action_raiser varchar NOT NULL,
	opening_day_local_id int4 NULL,
	opening_local_ts timestamp NULL,
	opening_utc_ts timestamp NULL,
	due_date_day_local_id int4 NULL,
	due_date_local_ts timestamp NULL,
	due_date_utc_ts timestamp NULL,
	creation_day_local_id int4 NOT NULL,
	creation_local_ts timestamp NOT NULL,
	creation_utc_ts timestamp DEFAULT timezone('utc'::text, CURRENT_TIMESTAMP) NOT NULL,
	creator_user varchar NOT NULL,
	kpi_category_cd varchar NULL,
	owner_id int8 NULL,
	CONSTRAINT pk_lk_pending_actions PRIMARY KEY (plant_id, action_id)
);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions ON application_data.lk_pending_actions USING btree (module_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_1 ON application_data.lk_pending_actions USING btree (line_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_10 ON application_data.lk_pending_actions USING btree (due_date_day_local_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_15 ON application_data.lk_pending_actions USING btree (plant_id, module_id, line_id, kpi_category_id, action_id, action_status_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_17 ON application_data.lk_pending_actions USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_18 ON application_data.lk_pending_actions USING btree (action_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_19 ON application_data.lk_pending_actions USING btree (action_cd);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_20 ON application_data.lk_pending_actions USING btree (opening_tier_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_21 ON application_data.lk_pending_actions USING btree (assign_tier_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_3 ON application_data.lk_pending_actions USING btree (action_priority_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_4 ON application_data.lk_pending_actions USING btree (action_status_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_5 ON application_data.lk_pending_actions USING btree (kpi_category_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_6 ON application_data.lk_pending_actions USING btree (opening_tier_id);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_7 ON application_data.lk_pending_actions USING btree (action_owner);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_8 ON application_data.lk_pending_actions USING btree (action_raiser);
CREATE INDEX IF NOT EXISTS idx_lk_pending_actions_9 ON application_data.lk_pending_actions USING btree (opening_day_local_id);


-- DROP TABLE application_data.sh_lk_shift_sort;

CREATE TABLE IF NOT EXISTS application_data.sh_lk_shift_sort (
	sh_sort_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	sh_sort_cd varchar(70) NULL,
	sh_sort_ds varchar(500) NULL,
	CONSTRAINT pk_sh_lk_shift_sort PRIMARY KEY (sh_sort_id),
	CONSTRAINT uq_sh_lk_shift_sort UNIQUE (sh_sort_cd)
);



-- Drop table

-- DROP TABLE application_data.sh_lk_pattern;

CREATE TABLE IF NOT EXISTS application_data.sh_lk_pattern (
	plant_id int8 NOT NULL,
	pattern_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 100 MINVALUE 1 MAXVALUE 9223372036854775807 START 100 CACHE 1 NO CYCLE) NOT NULL,
	pattern_cd varchar(100) NOT NULL,
	pattern_ds varchar(500) NULL,
	is_deleted int4 DEFAULT 0 NOT NULL,
	is_default int4 NULL,
	au_user_id int8 NULL,
	au_change_type varchar(10) NULL,
	au_change_num int8 NULL,
	au_change_day_id int4 NULL,
	au_change_ts timestamp(0) NULL,
	is_modify int4 DEFAULT 1 NOT NULL,
	is_active int4 DEFAULT 1 NULL,
	CONSTRAINT pk_sh_lk_pattern PRIMARY KEY (plant_id, pattern_id),
	CONSTRAINT uq_sh_lk_pattern UNIQUE (plant_id, pattern_cd)
);
CREATE INDEX IF NOT EXISTS idx_sh_lk_pattern ON application_data.sh_lk_pattern USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS idx_sh_lk_pattern_0 ON application_data.sh_lk_pattern USING btree (is_default);
CREATE INDEX IF NOT EXISTS idx_sh_lk_pattern_1 ON application_data.sh_lk_pattern USING btree (is_modify);
CREATE INDEX IF NOT EXISTS idx_sh_lk_pattern_2 ON application_data.sh_lk_pattern USING btree (is_active);
CREATE INDEX IF NOT EXISTS idx_sh_lk_pattern_3 ON application_data.sh_lk_pattern USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_pattern_4 ON application_data.sh_lk_pattern USING btree (pattern_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_pattern_5 ON application_data.sh_lk_pattern USING btree (pattern_cd);


-- application_data.sh_lk_line_calendar definition

-- Drop table

-- DROP TABLE application_data.sh_lk_line_calendar;

CREATE TABLE IF NOT EXISTS application_data.sh_lk_line_calendar (
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	day_id int4 NOT NULL,
	def_pattern_id int8 NULL,
	pattern_id int8 NULL,
	shift_id int8 NOT NULL,
	shift_sort int4 NOT NULL,
	shift_start_dt timestamp NULL,
	shift_end_dt timestamp NULL,
	is_no_working_day int4 NOT NULL,
	is_holiday int4 NOT NULL,
	is_scheduled_to_run int4 NOT NULL,
	shift_number int4 NOT NULL,
	working_duration_sec numeric(20, 5) NOT NULL,
	au_user_id int8 NULL,
	au_change_type varchar(10) NULL,
	au_change_num int8 NULL,
	au_change_day_id int4 NULL,
	au_change_ts timestamp NULL,
	is_modify int4 DEFAULT 1 NOT NULL,
	shift_start_dt_utc timestamp NULL,
	shift_end_dt_utc timestamp NULL,
	day_id_utc int4 NOT NULL,
	CONSTRAINT pk_sh_lk_line_calendar PRIMARY KEY (plant_id, line_id, day_id, shift_id)
);
CREATE INDEX IF NOT EXISTS idx2_sh_lk_line_calendar ON application_data.sh_lk_line_calendar USING btree (plant_id, day_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar ON application_data.sh_lk_line_calendar USING btree (def_pattern_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_0 ON application_data.sh_lk_line_calendar USING btree (pattern_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_1 ON application_data.sh_lk_line_calendar USING btree (is_scheduled_to_run);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_2 ON application_data.sh_lk_line_calendar USING btree (is_modify);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_3 ON application_data.sh_lk_line_calendar USING btree (shift_sort);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_4 ON application_data.sh_lk_line_calendar USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_5 ON application_data.sh_lk_line_calendar USING btree (line_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_6 ON application_data.sh_lk_line_calendar USING btree (day_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_7 ON application_data.sh_lk_line_calendar USING btree (shift_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_8 ON application_data.sh_lk_line_calendar USING btree (is_no_working_day);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_calendar_9 ON application_data.sh_lk_line_calendar USING btree (is_holiday);


-- application_data.sh_lk_line_pattern_default definition

-- Drop table

-- DROP TABLE application_data.sh_lk_line_pattern_default;

CREATE TABLE IF NOT EXISTS application_data.sh_lk_line_pattern_default (
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	week_day_id int4 NOT NULL,
	pattern_id int8 NULL,
	au_user_id int8 NULL,
	au_change_type varchar(10) NULL,
	au_change_num int8 NULL,
	au_change_day_id int4 DEFAULT to_char(timezone('UTC', current_timestamp),'YYYYMMDD')::int,
	au_change_ts timestamp(0) DEFAULT timezone('UTC', current_timestamp),
	is_modify int4 DEFAULT 1 NOT NULL,
	CONSTRAINT pk_sh_lk_line_pattern_default PRIMARY KEY (plant_id, line_id, week_day_id)
);
CREATE INDEX IF NOT EXISTS fki_fk_sh_lk_line_pattern_default_lk_line ON application_data.sh_lk_line_pattern_default USING btree (plant_id, line_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_pattern_default ON application_data.sh_lk_line_pattern_default USING btree (pattern_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_pattern_default_0 ON application_data.sh_lk_line_pattern_default USING btree (is_modify);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_pattern_default_1 ON application_data.sh_lk_line_pattern_default USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_pattern_default_2 ON application_data.sh_lk_line_pattern_default USING btree (line_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_line_pattern_default_3 ON application_data.sh_lk_line_pattern_default USING btree (week_day_id);

-- application_data.sh_lk_shift definition

-- Drop table

-- DROP TABLE application_data.sh_lk_shift;

CREATE TABLE IF NOT EXISTS application_data.sh_lk_shift (
	plant_id int8 NOT NULL,
	shift_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	shift_cd varchar(100) NOT NULL,
	shift_short_cd varchar(100) NULL,
	shift_ds varchar(500) NULL,
	start_time_desc varchar(500) NOT NULL,
	start_time_offset int4 NOT NULL,
	end_time_desc varchar(500) NOT NULL,
	end_time_offset int4 NOT NULL,
	duration_ss int4 NOT NULL,
	is_deleted int4 NOT NULL,
	au_user_id int8 NULL,
	au_change_type varchar(10) NULL,
	au_change_num int8 NULL,
	au_change_day_id int4 NULL,
	au_change_ts timestamp(0) NULL,
	shift_src_id int8 NOT NULL,
	CONSTRAINT pk_sh_lk_shift PRIMARY KEY (plant_id, shift_id),
	CONSTRAINT uq_sh_lk_shift UNIQUE (plant_id, shift_cd)
);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift ON application_data.sh_lk_shift USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_0 ON application_data.sh_lk_shift USING btree (shift_src_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_1 ON application_data.sh_lk_shift USING btree (shift_short_cd);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_2 ON application_data.sh_lk_shift USING btree (shift_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_3 ON application_data.sh_lk_shift USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_4 ON application_data.sh_lk_shift USING btree (shift_cd);


-- application_data.sh_lk_shift_definition definition

-- Drop table

-- DROP TABLE application_data.sh_lk_shift_definition;

CREATE TABLE IF NOT EXISTS application_data.sh_lk_shift_definition (
	plant_id int8 NOT NULL,
	shift_def_id int8 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	shift_def_cd varchar(100) NOT NULL,
	shift_def_short_cd varchar(100) NULL,
	shift_def_ds varchar(500) NULL,
	start_time_desc varchar(500) NOT NULL,
	start_time_offset int4 NOT NULL,
	end_time_desc varchar(500) NOT NULL,
	end_time_offset int4 NOT NULL,
	duration_ss int4 NOT NULL,
	is_deleted int4 DEFAULT 0 NOT NULL,
	au_user_id int8 NULL,
	au_change_type varchar(10) NULL,
	au_change_num int8 NULL,
	au_change_day_id int4 NULL,
	au_change_ts timestamp(0) NULL,
	is_modify int4 DEFAULT 1 NOT NULL,
	CONSTRAINT pk_sh_lk_shift_definition PRIMARY KEY (plant_id, shift_def_id),
	CONSTRAINT uq_sh_lk_shift_definition UNIQUE (plant_id, shift_def_cd)
);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_definition ON application_data.sh_lk_shift_definition USING btree (is_deleted);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_definition_0 ON application_data.sh_lk_shift_definition USING btree (is_modify);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_definition_1 ON application_data.sh_lk_shift_definition USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_definition_2 ON application_data.sh_lk_shift_definition USING btree (shift_def_id);
CREATE INDEX IF NOT EXISTS idx_sh_lk_shift_definition_3 ON application_data.sh_lk_shift_definition USING btree (shift_def_cd);


-- application_data.sh_map_pattern_shift definition

-- Drop table

-- DROP TABLE application_data.sh_map_pattern_shift;

CREATE TABLE IF NOT EXISTS application_data.sh_map_pattern_shift (
	plant_id int8 NOT NULL,
	pattern_id int8 NOT NULL,
	shift_def_id int8 NOT NULL,
	shift_sort int4 NOT NULL,
	au_user_id int8 NULL,
	au_change_type varchar(10) NULL,
	au_change_num int8 NULL,
	au_change_day_id int4 NULL,
	au_change_ts timestamp NULL,
	CONSTRAINT pk_sh_map_pattern_shift PRIMARY KEY (plant_id, pattern_id, shift_def_id),
	CONSTRAINT uq_sh_map_pattern_shift UNIQUE (plant_id, pattern_id, shift_sort)
);
CREATE INDEX IF NOT EXISTS idx_sh_map_pattern_shift ON application_data.sh_map_pattern_shift USING btree (shift_sort);
CREATE INDEX IF NOT EXISTS idx_sh_map_pattern_shift_0 ON application_data.sh_map_pattern_shift USING btree (plant_id);
CREATE INDEX IF NOT EXISTS idx_sh_map_pattern_shift_1 ON application_data.sh_map_pattern_shift USING btree (pattern_id);
CREATE INDEX IF NOT EXISTS idx_sh_map_pattern_shift_2 ON application_data.sh_map_pattern_shift USING btree (shift_def_id);


CREATE TABLE IF NOT EXISTS application_data.lk_non_production_days (
	non_production_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 10 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NULL,
	"year" int4 NOT NULL,
	non_working_date date NOT NULL,
	non_working_day_id numeric(8) NOT NULL,
	reason varchar(100) NULL,
	is_holiday int4 DEFAULT 0 NOT NULL,
	is_scheduled_to_run int4 DEFAULT 0 NOT NULL,
	is_no_working_day int4 DEFAULT 1 NOT NULL,
	creator_user varchar NOT NULL,
	creation_ts timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'::text) NOT NULL,
	last_user varchar NOT NULL,
	last_modified timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'::text) NOT NULL,
	CONSTRAINT pk_plant_non_production_days PRIMARY KEY (non_production_id),
	CONSTRAINT uq_plant_non_working_days UNIQUE (plant_id, line_id, non_working_day_id)
);


-- DROP TABLE application_data.lk_time;

CREATE TABLE IF NOT EXISTS application_data.lk_time (
	time_id int8 NOT NULL,
	time_cd varchar(70) NULL,
	time_ds varchar(250) NULL,
	hour_cd varchar(70) NULL,
	hour_ds varchar(250) NULL,
	CONSTRAINT pk_lk_time PRIMARY KEY (time_id)
);
CREATE INDEX IF NOT EXISTS idx_lk_time ON application_data.lk_time USING btree (time_cd);


-- application_data.ft_shift

-- Drop table

-- DROP TABLE application_data.ft_shift;

CREATE TABLE IF NOT EXISTS application_data.ft_shift (
	shift_seq int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	plant_id int8 NOT NULL,
	line_id int8 NOT NULL,
	shift_id int8 NOT NULL,
	day_id_utc int4 NOT NULL,
	start_timestamp_utc timestamp NULL,
	end_timestamp_utc timestamp NULL,
	working_duration_sec numeric(20, 5) NOT NULL,
	is_manually_declared bool DEFAULT false NULL,
	start_timestamp_local timestamp NULL,
	end_timestamp_local timestamp NULL,
	day_id_local int4 NULL,
	CONSTRAINT pk_ft_shift_shift_seq PRIMARY KEY (shift_seq),
	CONSTRAINT uq_ft_shift UNIQUE (plant_id, line_id, day_id_utc, shift_id)
);


-- application_data.ft_shift foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.ft_shift ADD CONSTRAINT fk_ft_shift_lk_line FOREIGN KEY (plant_id,line_id) REFERENCES application_data.lk_line(plant_id,line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE application_data.ft_shift ADD CONSTRAINT fk_ft_shift_sh_lk_shift FOREIGN KEY (plant_id,shift_id) REFERENCES application_data.sh_lk_shift(plant_id,shift_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;



-- application_data.lk_pending_actions foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_pending_actions ADD CONSTRAINT fk_lk_pending_actions_hi_lk_module FOREIGN KEY (plant_id,module_id) REFERENCES application_data.lk_module(plant_id,module_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_pending_actions ADD CONSTRAINT fk_lk_pending_actions_lk_action_priority FOREIGN KEY (action_priority_id) REFERENCES application_data.lk_action_priority(action_priority_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_pending_actions ADD CONSTRAINT fk_lk_pending_actions_lk_action_status FOREIGN KEY (action_status_id) REFERENCES application_data.lk_action_status(action_status_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_pending_actions ADD CONSTRAINT fk_lk_pending_actions_lk_line FOREIGN KEY (plant_id,line_id) REFERENCES application_data.lk_line(plant_id,line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_pending_actions ADD CONSTRAINT fk_lk_pending_actions_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_pending_actions ADD CONSTRAINT fk_lk_pending_actions_lk_tier FOREIGN KEY (plant_id,opening_tier_id) REFERENCES application_data.lk_tier(plant_id,tier_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;





-- application_data.ft_meeting foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.ft_meeting ADD CONSTRAINT fk_ft_meeting_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.ft_meeting ADD CONSTRAINT fk_ft_meeting_lk_tier FOREIGN KEY (plant_id,tier_id) REFERENCES application_data.lk_tier(plant_id,tier_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.map_attendance_tier foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.map_attendance_tier ADD CONSTRAINT fk_map_attendace_tier_lk_attendance_role FOREIGN KEY (plant_id,attendance_role_id) REFERENCES application_data.lk_attendance_role(plant_id,attendance_role_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.map_attendance_tier ADD CONSTRAINT fk_map_attendance_tier_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.map_attendance_tier ADD CONSTRAINT fk_map_attendance_tier_lk_tier FOREIGN KEY (plant_id,tier_id) REFERENCES application_data.lk_tier(plant_id,tier_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;




-- application_data.map_action_issue foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.map_action_issue ADD CONSTRAINT fk_map_action_issue_lk_action FOREIGN KEY (plant_id,action_id) REFERENCES application_data.lk_action(plant_id,action_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.map_action_issue ADD CONSTRAINT fk_map_action_issue_lk_issue FOREIGN KEY (plant_id,issue_id) REFERENCES application_data.lk_issue(plant_id,issue_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.map_action_issue ADD CONSTRAINT fk_map_action_issue_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;




-- application_data.ft_attendance foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.ft_attendance ADD CONSTRAINT fk_ft_attendance_lk_attendance_role FOREIGN KEY (plant_id,attendance_role_id) REFERENCES application_data.lk_attendance_role(plant_id,attendance_role_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.ft_attendance ADD CONSTRAINT fk_ft_attendance_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.ft_attendance ADD CONSTRAINT fk_ft_attendance_lk_status FOREIGN KEY (status_id) REFERENCES application_data.lk_attendance_status(at_status_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.ft_attendance ADD CONSTRAINT fk_ft_attendance_lk_tier FOREIGN KEY (plant_id,tier_id) REFERENCES application_data.lk_tier(plant_id,tier_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;




-- application_data.ass_module_line_tier_kpi foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.ass_module_line_tier_kpi ADD CONSTRAINT ass_module_line_tier_kpi_lk_kpi_fk FOREIGN KEY (plant_id,kpi_id) REFERENCES application_data.lk_kpi(plant_id,kpi_id) ON DELETE CASCADE ON UPDATE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.ass_module_line_tier_kpi ADD CONSTRAINT ass_module_line_tier_kpi_lk_line_fk FOREIGN KEY (plant_id,line_id) REFERENCES application_data.lk_line(plant_id,line_id) ON DELETE CASCADE ON UPDATE SET NULL;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.ass_module_line_tier_kpi ADD CONSTRAINT ass_module_line_tier_kpi_lk_tier_fk FOREIGN KEY (plant_id,tier_id) REFERENCES application_data.lk_tier(plant_id,tier_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;



-- application_data.lk_attendance_role foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_attendance_role ADD CONSTRAINT fk_attendance_role_code_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;



-- application_data.lk_tier foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_tier ADD CONSTRAINT lk_tier_lk_plant_fk FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.lk_external_link foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_external_link ADD CONSTRAINT fk_lk_external_link_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_external_link ADD CONSTRAINT fk_lk_external_link_lk_tier FOREIGN KEY (plant_id,tier_id) REFERENCES application_data.lk_tier(plant_id,tier_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;




-- application_data.lk_component foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_component ADD CONSTRAINT fk_lk_component_lk_machine FOREIGN KEY (machine_id,plant_id) REFERENCES application_data.lk_machine(machine_id,plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_component ADD CONSTRAINT fk_lk_component_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.lk_line foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_line ADD CONSTRAINT fk_lk_line_lk_module FOREIGN KEY (plant_id,module_id) REFERENCES application_data.lk_module(plant_id,module_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.lk_machine foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_machine ADD CONSTRAINT fk_lk_line FOREIGN KEY (line_id,plant_id) REFERENCES application_data.lk_line(line_id,plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_machine ADD CONSTRAINT fk_lk_machine_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.lk_module foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_module ADD CONSTRAINT lk_module_lk_plant_fk FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;



-- application_data.lk_issue foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_issue ADD CONSTRAINT lk_issue_lk_issue_status_fk FOREIGN KEY (issue_status_id) REFERENCES application_data.lk_issue_status(issue_status_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_issue ADD CONSTRAINT lk_issue_lk_kpi_category_fk FOREIGN KEY (plant_id,kpi_category_id) REFERENCES application_data.lk_kpi_category(plant_id,kpi_category_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_issue ADD CONSTRAINT lk_issue_lk_line_fk FOREIGN KEY (plant_id,line_id) REFERENCES application_data.lk_line(plant_id,line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_issue ADD CONSTRAINT lk_issue_lk_module_fk FOREIGN KEY (plant_id,module_id) REFERENCES application_data.lk_module(plant_id,module_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_issue ADD CONSTRAINT lk_issue_lk_plant_fk FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_issue ADD CONSTRAINT lk_issue_lk_tier_fk FOREIGN KEY (plant_id,opening_tier_id) REFERENCES application_data.lk_tier(plant_id,tier_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;




-- application_data.lk_kpi foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_kpi ADD CONSTRAINT fk_lk_kpi_lk_aggregation_role FOREIGN KEY (aggregation_rule_id) REFERENCES application_data.lk_aggregation_rule(aggregation_rule_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_kpi ADD CONSTRAINT fk_lk_kpi_lk_kpi_category FOREIGN KEY (plant_id,kpi_category_id) REFERENCES application_data.lk_kpi_category(plant_id,kpi_category_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_kpi ADD CONSTRAINT fk_lk_kpi_lk_kpi_group FOREIGN KEY (plant_id,kpi_group_id,kpi_category_id) REFERENCES application_data.lk_kpi_group(plant_id,kpi_group_id,kpi_category_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_kpi ADD CONSTRAINT fk_lk_kpi_lk_kpi_uom FOREIGN KEY (kpi_uom_id) REFERENCES application_data.lk_kpi_uom(kpi_uom_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_kpi ADD CONSTRAINT fk_lk_kpi_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_kpi ADD CONSTRAINT fk_lk_kpi_lk_target_tendency FOREIGN KEY (target_tendency_id) REFERENCES application_data.lk_target_tendency(target_tendency_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;



-- application_data.lk_kpi_group foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_kpi_group ADD CONSTRAINT fk_kpi_lk_group_kpi_lk_category FOREIGN KEY (kpi_category_id,plant_id) REFERENCES application_data.lk_kpi_category(kpi_category_id,plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_kpi_group ADD CONSTRAINT fk_kpi_lk_group_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;




-- application_data.lk_action foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.lk_action ADD CONSTRAINT fk_lk_actions_hi_lk_module FOREIGN KEY (plant_id,module_id) REFERENCES application_data.lk_module(plant_id,module_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_action ADD CONSTRAINT fk_lk_actions_lk_action_priority FOREIGN KEY (action_priority_id) REFERENCES application_data.lk_action_priority(action_priority_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_action ADD CONSTRAINT fk_lk_actions_lk_action_status FOREIGN KEY (action_status_id) REFERENCES application_data.lk_action_status(action_status_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_action ADD CONSTRAINT fk_lk_actions_lk_kpi_category FOREIGN KEY (plant_id,kpi_category_id) REFERENCES application_data.lk_kpi_category(plant_id,kpi_category_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_action ADD CONSTRAINT fk_lk_actions_lk_line FOREIGN KEY (plant_id,line_id) REFERENCES application_data.lk_line(plant_id,line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_action ADD CONSTRAINT fk_lk_actions_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.lk_action ADD CONSTRAINT fk_lk_actions_lk_tier FOREIGN KEY (plant_id,opening_tier_id) REFERENCES application_data.lk_tier(plant_id,tier_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- application_data.ft_pareto_data foreign keys
DO $$ BEGIN
    ALTER TABLE application_data.ft_pareto_data ADD CONSTRAINT ft_pareto_data_lk_kpi_fk FOREIGN KEY (plant_id, kpi_id) REFERENCES application_data.lk_kpi(plant_id, kpi_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- application_data.ft_kpi_target foreign keys
DO $$ BEGIN
    ALTER TABLE application_data.ft_kpi_target ADD CONSTRAINT ft_kpi_target_lk_kpi_fk FOREIGN KEY (plant_id,kpi_id) REFERENCES application_data.lk_kpi(plant_id,kpi_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.sh_lk_line_calendar foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.sh_lk_line_calendar ADD CONSTRAINT fk_sh_lk_line_calendar_lk_line FOREIGN KEY (plant_id,line_id) REFERENCES application_data.lk_line(plant_id,line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.sh_lk_line_calendar ADD CONSTRAINT fk_sh_lk_line_calendar_sh_lk_shift FOREIGN KEY (plant_id,shift_id) REFERENCES application_data.sh_lk_shift(plant_id,shift_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.sh_lk_line_calendar ADD CONSTRAINT fk_sh_lk_line_calendar_sh_lk_shift_sort FOREIGN KEY (shift_sort) REFERENCES application_data.sh_lk_shift_sort(sh_sort_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.sh_lk_line_pattern_default foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.sh_lk_line_pattern_default ADD CONSTRAINT fk_sh_lk_line_pattern_default_lk_line FOREIGN KEY (plant_id,line_id) REFERENCES application_data.lk_line(plant_id,line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.sh_lk_line_pattern_default ADD CONSTRAINT fk_sh_lk_line_pattern_default_sh_lk_pattern FOREIGN KEY (plant_id,pattern_id) REFERENCES application_data.sh_lk_pattern(plant_id,pattern_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.sh_lk_shift foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.sh_lk_shift ADD CONSTRAINT fk_sh_lk_shift_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.sh_lk_shift_definition foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.sh_lk_shift_definition ADD CONSTRAINT fk_sh_lk_shift_definition_lk_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- application_data.sh_map_pattern_shift foreign keys

DO $$ BEGIN
    ALTER TABLE application_data.sh_map_pattern_shift ADD CONSTRAINT fk_sh_map_pattern_shift_sh_lk_pattern FOREIGN KEY (plant_id,pattern_id) REFERENCES application_data.sh_lk_pattern(plant_id,pattern_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.sh_map_pattern_shift ADD CONSTRAINT fk_sh_map_pattern_shift_sh_lk_shift_definition FOREIGN KEY (plant_id,shift_def_id) REFERENCES application_data.sh_lk_shift_definition(plant_id,shift_def_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
    ALTER TABLE application_data.sh_map_pattern_shift ADD CONSTRAINT fk_sh_map_pattern_shift_sh_lk_shift_sort FOREIGN KEY (shift_sort) REFERENCES application_data.sh_lk_shift_sort(sh_sort_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
    ALTER TABLE application_data.lk_non_production_days ADD CONSTRAINT fk_plant_non_working_days_plant FOREIGN KEY (plant_id,line_id) REFERENCES application_data.lk_line(plant_id,line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;


-- DWH lookup uniqueness alignment (multi-line):
-- allow same shift/code per plant across different lines by including line_id in business key.
DO $$
BEGIN
    IF to_regclass('application_data.lk_shift_dwh') IS NOT NULL THEN
        ALTER TABLE application_data.lk_shift_dwh
            ALTER COLUMN line_id SET NOT NULL;
        ALTER TABLE application_data.lk_shift_dwh
            DROP CONSTRAINT IF EXISTS uk_lk_shift_dwh;
        ALTER TABLE application_data.lk_shift_dwh
            ADD CONSTRAINT uk_lk_shift_dwh UNIQUE (plant_id, line_id, shift_code);
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('application_data.lk_code') IS NOT NULL THEN
        ALTER TABLE application_data.lk_code
            ADD COLUMN IF NOT EXISTS source_codetype_key varchar(255);
        ALTER TABLE application_data.lk_code
            ADD COLUMN IF NOT EXISTS source_codetype_description text;
        ALTER TABLE application_data.lk_code
            ALTER COLUMN line_id SET NOT NULL;
        ALTER TABLE application_data.lk_code
            DROP CONSTRAINT IF EXISTS uk_lk_code;
        ALTER TABLE application_data.lk_code
            ADD CONSTRAINT uk_lk_code UNIQUE (plant_id, line_id, code_code, code_type_source_id);
    END IF;
END $$;



-- application_data.ft_kpi_target_seq

CREATE SEQUENCE IF NOT EXISTS application_data.ft_kpi_target_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
	
-- application_data.lk_action_id_seq definition

-- DROP SEQUENCE application_data.lk_action_id_seq;

CREATE SEQUENCE IF NOT EXISTS application_data.lk_action_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;


-- application_data.lk_issue_id_seq definition

-- DROP SEQUENCE application_data.lk_issue_id_seq;

CREATE SEQUENCE IF NOT EXISTS application_data.lk_issue_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
	
	
	-- application_data.ft_pareto_data_seq definition

-- DROP SEQUENCE application_data.ft_pareto_data_seq;

CREATE SEQUENCE IF NOT EXISTS application_data.ft_pareto_data_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;