-- ==============================================================
-- Script: 8_dwh_integration_ddl.sql
-- Purpose: DDL per integrazione dati da DWH SQL Server multi-linea
-- Scope:   Nuove tabelle lookup + fact table
--
-- Run as:  tenant_<tenantID>_user
-- Target:  Database: dlmo_tenant_<tenantID>_db
--
-- Order:   8 - Dopo 7_insert_default_data.sql
--
-- Prerequisiti: 
--   - Eseguire prima 9_migration_add_source_id.sql per aggiungere
--     source_id a lk_plant, lk_line, lk_machine, lk_component
--
-- Version: 1.0.0
-- Last updated: 2026-02-04
-- ==============================================================

-- ================================================================
-- NUOVE TABELLE LOOKUP PER ENTITÀ DWH
-- ================================================================

-- -----------------------------------------------------
-- lk_code (da [sp203_an].[Code])
-- Nota: CodeType non viene importato, solo code_type_source_id per tracciabilità
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS application_data.lk_code (
    code_id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 100 START 100) NOT NULL,
    code_code varchar(255) NOT NULL,
    code_ds varchar(500) NULL,
    plant_id int8 NOT NULL,
    line_id int8 NOT NULL,                  -- FK → lk_line (Codes are per-line)
    source_id int4 NULL,                    -- CodeIntId originale
    code_type_source_id int4 NULL,          -- CodeTypeIntId originale (solo per tracciabilità)
    source_codetype_key varchar(255) NULL,  -- CodeTypeKey da [sp203_an].[CodeType]
    source_codetype_description text NULL,  -- Description da [sp203_an].[CodeType]
    is_active bool DEFAULT true NOT NULL,
    is_deleted bool DEFAULT false NOT NULL,
    creation_ts timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NOT NULL,
    creator_user varchar NOT NULL,
    last_modified timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NULL,
    last_user varchar NOT NULL,
    CONSTRAINT pk_lk_code PRIMARY KEY (code_id),
    CONSTRAINT uk_lk_code UNIQUE (plant_id, line_id, code_code, code_type_source_id)
);
-- Indice su source_id per performance; non più univoco perché i source_id possono coincidere tra DWH
CREATE INDEX IF NOT EXISTS lk_code_source_idx 
  ON application_data.lk_code (line_id, source_id) 
  WHERE source_id IS NOT NULL;

COMMENT ON TABLE application_data.lk_code IS 'Codici (es. codici scarto/difetto) - origine: [sp203_an].[Code]';


-- -----------------------------------------------------
-- lk_shift_dwh (da [sp203_an].[Shift])
-- Nota: distinta da sh_lk_shift che è per lo scheduling interno
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS application_data.lk_shift_dwh (
    shift_dwh_id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 100 START 100) NOT NULL,
    shift_code varchar(50) NOT NULL,
    shift_ds varchar(255) NULL,
    shift_start_time time NULL,
    shift_end_time time NULL,
    plant_id int8 NOT NULL,
    line_id int8 NOT NULL,                  -- FK → lk_line (Shifts are per-line)
    source_id int4 NULL,                    -- ShiftIntId originale
    is_active bool DEFAULT true NOT NULL,
    is_deleted bool DEFAULT false NOT NULL,
    creation_ts timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NOT NULL,
    creator_user varchar NOT NULL,
    last_modified timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NULL,
    last_user varchar NOT NULL,
    CONSTRAINT pk_lk_shift_dwh PRIMARY KEY (shift_dwh_id),
    CONSTRAINT uk_lk_shift_dwh UNIQUE (plant_id, line_id, shift_code)
);
CREATE INDEX IF NOT EXISTS lk_shift_dwh_source_idx 
  ON application_data.lk_shift_dwh (line_id, source_id) 
  WHERE source_id IS NOT NULL;

COMMENT ON TABLE application_data.lk_shift_dwh IS 'Turni da DWH sorgente - origine: [sp203_an].[Shift]';


-- -----------------------------------------------------
-- lk_fixture (da [sp203_an].[Fixture])
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS application_data.lk_fixture (
    fixture_id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 100 START 100) NOT NULL,
    fixture_code varchar(50) NOT NULL,
    fixture_ds varchar(255) NULL,
    plant_id int8 NOT NULL,
    line_id int8 NOT NULL,
    component_id int8 NULL,                 -- FK → lk_component (machine DWH)
    source_id int4 NULL,                    -- FixtureIntId originale
    source_machine_id int4 NULL,            -- MachineIntId originale (per tracciabilità)
    is_active bool DEFAULT true NOT NULL,
    is_deleted bool DEFAULT false NOT NULL,
    creation_ts timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NOT NULL,
    creator_user varchar NOT NULL,
    last_modified timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NULL,
    last_user varchar NOT NULL,
    CONSTRAINT pk_lk_fixture PRIMARY KEY (fixture_id),
    CONSTRAINT uk_lk_fixture_source_component UNIQUE (plant_id, line_id, source_id, component_id)
);
CREATE INDEX IF NOT EXISTS lk_fixture_source_idx 
  ON application_data.lk_fixture (plant_id, line_id, source_id) 
  WHERE source_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS lk_fixture_component_idx ON application_data.lk_fixture (component_id);
CREATE INDEX IF NOT EXISTS lk_fixture_line_source_component_idx
  ON application_data.lk_fixture (line_id, source_id, component_id)
  WHERE source_id IS NOT NULL AND component_id IS NOT NULL;

COMMENT ON TABLE application_data.lk_fixture IS 'Attrezzature/fixture - origine: [sp203_an].[Fixture]; una riga per (fixture sorgente, component/step) per ft_rawdata fixture_id per step';


-- -----------------------------------------------------
-- lk_result (da [sp203_an].[Result])
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS application_data.lk_result (
    result_id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 100 START 100) NOT NULL,
    result_code varchar(50) NOT NULL,
    result_ds varchar(255) NULL,
    is_good bool NOT NULL,
    plant_id int8 NOT NULL,
    line_id int8 NOT NULL,                  -- FK → lk_line (Results are per-line)
    machine_id int8 NULL,                   -- FK → lk_machine (step) - opzionale
    source_id int4 NULL,                    -- ResultIntId originale
    step_source_id int4 NULL,               -- StepIntId originale
    is_active bool DEFAULT true NOT NULL,
    is_deleted bool DEFAULT false NOT NULL,
    creation_ts timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NOT NULL,
    creator_user varchar NOT NULL,
    last_modified timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NULL,
    last_user varchar NOT NULL,
    CONSTRAINT pk_lk_result PRIMARY KEY (result_id),
    CONSTRAINT uk_lk_result UNIQUE (line_id, result_code, machine_id)
);
CREATE INDEX IF NOT EXISTS lk_result_source_idx 
  ON application_data.lk_result (line_id, source_id) 
  WHERE source_id IS NOT NULL;

COMMENT ON TABLE application_data.lk_result IS 'Risultati (OK/KO) - origine: [sp203_an].[Result]';


-- ================================================================
-- lk_production_time_date (da [sp203_an].[ProductionTimeDate])
-- Calendario produzione DWH: una riga per data PER LINEA.
-- SourceId non è globalmente univoco tra sorgenti, quindi l'univocità è line-scoped.
-- ================================================================
CREATE TABLE IF NOT EXISTS application_data.lk_production_time_date (
    production_time_date_id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 START 1) NOT NULL,
    line_id int8 NOT NULL,                  -- FK → lk_line (line-scoped calendar key)
    source_id int4 NOT NULL,                -- DWH ProductionTimeDate.Id (univoco nel perimetro line_id)
    production_date date NOT NULL,          -- Data di produzione
    id_day numeric(8) NOT NULL,              -- YYYYMMDD per join con lk_date
    year_num int4 NOT NULL,
    month_num int4 NOT NULL,
    day_num int4 NOT NULL,
    weekday_name varchar(50) NULL,
    week_number int4 NULL,
    quarter_num int4 NULL,
    CONSTRAINT pk_lk_production_time_date PRIMARY KEY (production_time_date_id),
    CONSTRAINT uk_lk_production_time_date_source UNIQUE (line_id, source_id),
    CONSTRAINT uk_lk_production_time_date_id_day UNIQUE (line_id, id_day)
);

COMMENT ON TABLE application_data.lk_production_time_date IS 'Calendario date produzione da DWH per linea - origine: [sp203_an].[ProductionTimeDate].';


-- ================================================================
-- PARTE 3: FACT TABLE ft_rawdata
-- (dati da DeviceOnStepGrouped, snowflake)
-- Partizionamento: LIST(plant_id) poi RANGE(day_id) mensile (come ft_attendance).
-- Usare create_plant_partition + create_monthly_partition da 4_create_function_procedure.sql.
-- ================================================================

CREATE TABLE IF NOT EXISTS application_data.ft_rawdata (
    rawdata_id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 START 1) NOT NULL,
    
    -- Chiavi SORGENTE (per tracciabilità e lookup verso DWH)
    source_date_id int4 NOT NULL,           -- ProductionTimeDateId originale
    source_code_id int4 NULL,               -- CodeIntId originale
    source_fixture_id int4 NOT NULL,        -- FixtureIntId originale
    source_result_id int4 NULL,             -- ResultIntId originale
    source_site_id int2 NOT NULL,           -- SiteIntId originale
    source_step_id int4 NOT NULL,           -- StepIntId originale
    source_shift_id int4 NOT NULL,          -- ShiftIntId originale
    pass_number int2 NOT NULL,              -- PassNumber (non serve mappatura)
    
    -- Chiavi TARGET (FK verso tabelle del sistema, generate da sequence)
    day_id numeric(8) NOT NULL,             -- YYYYMMDD per join con lk_date
    plant_id int8 NOT NULL,                 -- FK → lk_plant
    line_id int8 NOT NULL,                  -- FK → lk_line
    machine_id int8 NOT NULL,               -- FK → lk_machine (step)
    component_id int8 NULL,                 -- FK → lk_component (machine DWH) - tramite fixture
    fixture_id int8 NOT NULL,               -- FK → lk_fixture
    code_id int8 NULL,                      -- FK → lk_code
    result_id int8 NULL,                    -- FK → lk_result
    shift_dwh_id int8 NOT NULL,             -- FK → lk_shift_dwh
    process_key text NULL,                  -- Process.ProcessKey (line/process scope for BY_PROCESS)
    is_redundant boolean DEFAULT false NOT NULL, -- True when source machine is mapped to multiple lines
    redundancy_rank int4 DEFAULT 1 NOT NULL, -- Deterministic rank in redundant groups (1 for non-redundant)
    
    -- Metriche
    total_production int8 NOT NULL,
    cycle_time_avg_sec numeric(12,3) NULL,
    work_time_avg_sec numeric(12,3) NULL,
    work_time_total_sec numeric(12,3) NULL,
    
    -- Audit
    etl_batch_id varchar(50) NULL,          -- Identificativo batch ETL
    etl_loaded_ts timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NOT NULL,
    
    CONSTRAINT pk_ft_rawdata PRIMARY KEY (rawdata_id, plant_id, day_id)
) PARTITION BY LIST (plant_id);

-- Backward-compatible adjustments for existing environments
ALTER TABLE application_data.ft_rawdata
    ADD COLUMN IF NOT EXISTS process_key text;
ALTER TABLE application_data.ft_rawdata
    ADD COLUMN IF NOT EXISTS is_redundant boolean DEFAULT false NOT NULL;
ALTER TABLE application_data.ft_rawdata
    ADD COLUMN IF NOT EXISTS redundancy_rank int4 DEFAULT 1 NOT NULL;

-- Indici per performance query
CREATE INDEX IF NOT EXISTS ft_rawdata_day_idx ON application_data.ft_rawdata (day_id);
CREATE INDEX IF NOT EXISTS ft_rawdata_plant_line_idx ON application_data.ft_rawdata (plant_id, line_id);
CREATE INDEX IF NOT EXISTS ft_rawdata_machine_idx ON application_data.ft_rawdata (machine_id);
CREATE INDEX IF NOT EXISTS ft_rawdata_fixture_idx ON application_data.ft_rawdata (fixture_id);
CREATE INDEX IF NOT EXISTS ft_rawdata_shift_idx ON application_data.ft_rawdata (shift_dwh_id);

-- Recreate unique index with line/process scope for idempotent load keys
DROP INDEX IF EXISTS application_data.ft_rawdata_source_uidx;
CREATE UNIQUE INDEX IF NOT EXISTS ft_rawdata_source_uidx ON application_data.ft_rawdata (
    plant_id, line_id, day_id, source_date_id, source_step_id, source_fixture_id, 
    COALESCE(process_key, ''),
    source_shift_id, pass_number, COALESCE(source_code_id, -1), COALESCE(source_result_id, -1)
);

COMMENT ON TABLE application_data.ft_rawdata IS 'Fact table dati produzione - origine: [dbo].[DeviceOnStepGrouped]';


-- ================================================================
-- PARTE 3b: SUPPORT FACT TABLE ft_quality (FPY staging)
-- Tabella di appoggio per calcolo First Pass Yield:
-- - contiene conteggi per giorno con dettaglio (component, fixture, shift)
-- - NON contiene il KPI (rapporto), ma i componenti del calcolo (good/total first pass)
-- ================================================================
CREATE TABLE IF NOT EXISTS application_data.ft_quality (
    quality_id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 START 1) NOT NULL,
    plant_id int8 NOT NULL,
    line_id int8 NOT NULL,
    day_id numeric(8) NOT NULL,                 -- YYYYMMDD (match ft_kpi_target.target_date_iso)
    production_date date NOT NULL,              -- Data (derivata da day_id)
    shift_dwh_id int8 NOT NULL,                 -- FK → lk_shift_dwh
    machine_id int8 NOT NULL,                   -- FK → lk_machine (step)
    component_id int8 NULL,                     -- FK → lk_component
    fixture_id int8 NOT NULL,                   -- FK → lk_fixture
    good_first_pass int8 NOT NULL,              -- Pezzi buoni al primo passaggio (pass_number=1 AND lk_result.is_good=true)
    total_first_pass int8 NOT NULL,             -- Pezzi totali primo passaggio (pass_number=1)
    calc_ts timestamp DEFAULT timezone('utc', CURRENT_TIMESTAMP) NOT NULL,
    calc_caller varchar(255) NULL,
    CONSTRAINT pk_ft_quality PRIMARY KEY (quality_id, plant_id, day_id)
) PARTITION BY LIST (plant_id);

-- Unicità logica: una riga per combinazione (giorno, shift, step/component, fixture)
CREATE UNIQUE INDEX IF NOT EXISTS ft_quality_uidx ON application_data.ft_quality (
    plant_id, line_id, day_id, shift_dwh_id, machine_id, COALESCE(component_id, -1), fixture_id
);
CREATE INDEX IF NOT EXISTS ft_quality_day_idx ON application_data.ft_quality (day_id);
CREATE INDEX IF NOT EXISTS ft_quality_plant_line_idx ON application_data.ft_quality (plant_id, line_id);

COMMENT ON TABLE application_data.ft_quality IS 'Support fact per qualità/FPY: conteggi first-pass good/total per giorno con dettaglio component/fixture/shift.';


-- ================================================================
-- PARTE 4: FOREIGN KEYS
-- ================================================================

-- lk_fixture → lk_component (una riga per component/step)
DO $$ BEGIN
    ALTER TABLE application_data.lk_fixture 
      ADD CONSTRAINT fk_lk_fixture_component 
      FOREIGN KEY (component_id) REFERENCES application_data.lk_component(component_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- lk_fixture → lk_line
DO $$ BEGIN
    ALTER TABLE application_data.lk_fixture 
      ADD CONSTRAINT fk_lk_fixture_line 
      FOREIGN KEY (plant_id, line_id) REFERENCES application_data.lk_line(plant_id, line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- lk_result → lk_machine (opzionale)
DO $$ BEGIN
    ALTER TABLE application_data.lk_result 
      ADD CONSTRAINT fk_lk_result_machine 
      FOREIGN KEY (machine_id, plant_id) REFERENCES application_data.lk_machine(machine_id, plant_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- lk_result → lk_line
DO $$ BEGIN
    ALTER TABLE application_data.lk_result 
      ADD CONSTRAINT fk_lk_result_line 
      FOREIGN KEY (plant_id, line_id) REFERENCES application_data.lk_line(plant_id, line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- lk_code → lk_line
DO $$ BEGIN
    ALTER TABLE application_data.lk_code 
      ADD CONSTRAINT fk_lk_code_line 
      FOREIGN KEY (plant_id, line_id) REFERENCES application_data.lk_line(plant_id, line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- lk_shift_dwh → lk_line
DO $$ BEGIN
    ALTER TABLE application_data.lk_shift_dwh 
      ADD CONSTRAINT fk_lk_shift_dwh_line 
      FOREIGN KEY (plant_id, line_id) REFERENCES application_data.lk_line(plant_id, line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- lk_production_time_date → lk_line
DO $$ BEGIN
    ALTER TABLE application_data.lk_production_time_date
      ADD CONSTRAINT fk_lk_production_time_date_line
      FOREIGN KEY (line_id) REFERENCES application_data.lk_line(line_id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Riallino vincoli unique per ambienti già esistenti (multi-line per plant).
DO $$
BEGIN
    IF to_regclass('application_data.lk_code') IS NOT NULL THEN
        ALTER TABLE application_data.lk_code
            ADD COLUMN IF NOT EXISTS source_codetype_key varchar(255);
        ALTER TABLE application_data.lk_code
            ADD COLUMN IF NOT EXISTS source_codetype_description text;
        ALTER TABLE application_data.lk_code
            DROP CONSTRAINT IF EXISTS uk_lk_code;
        ALTER TABLE application_data.lk_code
            ADD CONSTRAINT uk_lk_code UNIQUE (plant_id, line_id, code_code, code_type_source_id);
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('application_data.lk_shift_dwh') IS NOT NULL THEN
        ALTER TABLE application_data.lk_shift_dwh
            DROP CONSTRAINT IF EXISTS uk_lk_shift_dwh;
        ALTER TABLE application_data.lk_shift_dwh
            ADD CONSTRAINT uk_lk_shift_dwh UNIQUE (plant_id, line_id, shift_code);
    END IF;
END $$;

DO $$
BEGIN
    IF to_regclass('application_data.lk_production_time_date') IS NOT NULL THEN
        ALTER TABLE application_data.lk_production_time_date
            ADD COLUMN IF NOT EXISTS line_id int8;
        ALTER TABLE application_data.lk_production_time_date
            DROP CONSTRAINT IF EXISTS uk_lk_production_time_date_source;
        ALTER TABLE application_data.lk_production_time_date
            DROP CONSTRAINT IF EXISTS uk_lk_production_time_date_id_day;
        ALTER TABLE application_data.lk_production_time_date
            ADD CONSTRAINT uk_lk_production_time_date_source UNIQUE (line_id, source_id);
        ALTER TABLE application_data.lk_production_time_date
            ADD CONSTRAINT uk_lk_production_time_date_id_day UNIQUE (line_id, id_day);
    END IF;
END $$;

-- ft_rawdata FK (commentate per performance, si possono abilitare se necessario)
/*
ALTER TABLE application_data.ft_rawdata ADD CONSTRAINT fk_ft_rawdata_date FOREIGN KEY (day_id) REFERENCES application_data.lk_date(id_day);
ALTER TABLE application_data.ft_rawdata ADD CONSTRAINT fk_ft_rawdata_plant FOREIGN KEY (plant_id) REFERENCES application_data.lk_plant(plant_id);
ALTER TABLE application_data.ft_rawdata ADD CONSTRAINT fk_ft_rawdata_line FOREIGN KEY (plant_id, line_id) REFERENCES application_data.lk_line(plant_id, line_id);
ALTER TABLE application_data.ft_rawdata ADD CONSTRAINT fk_ft_rawdata_machine FOREIGN KEY (machine_id, plant_id) REFERENCES application_data.lk_machine(machine_id, plant_id);
ALTER TABLE application_data.ft_rawdata ADD CONSTRAINT fk_ft_rawdata_fixture FOREIGN KEY (fixture_id) REFERENCES application_data.lk_fixture(fixture_id);
ALTER TABLE application_data.ft_rawdata ADD CONSTRAINT fk_ft_rawdata_shift FOREIGN KEY (shift_dwh_id) REFERENCES application_data.lk_shift_dwh(shift_dwh_id);
*/


-- ================================================================
-- PARTE 5: PARTIZIONI ft_rawdata (come ft_attendance)
-- ft_rawdata: LIST(plant_id) -> partizione per plant -> RANGE(day_id) mensile.
-- La creazione partizioni è gestita dentro etl_sync_ft_rawdata tramite:
--   - application_data.create_plant_partition('ft_rawdata', 'day_id', plant_id)  -- se manca partizione plant
--   - application_data.create_monthly_partition('ft_rawdata', 'day_id', plant_id, year, month)  -- se manca partizione mensile
-- (Funzioni definite in 4_create_function_procedure.sql)
-- ================================================================


-- ================================================================
-- PARTE 6: TABELLA DI CONFIGURAZIONE SCHEMI SORGENTI DWH (FDW)
-- ---------------------------------------------------------------
-- Questa tabella configura quali schemi locali FDW (es. dwh_remote,
-- dwh_remote2, ...) rappresentano le diverse sorgenti DWH SQL Server
-- e permette alle procedure ETL di determinare dinamicamente quali
-- sorgenti processare (anche per gruppo logico).
-- ================================================================

CREATE SCHEMA IF NOT EXISTS application_staging AUTHORIZATION abb_prj_user;

CREATE TABLE IF NOT EXISTS application_staging.etl_source_schema_cfg (
    schema_name  TEXT PRIMARY KEY,                 -- es. 'dwh_remote', 'dwh_remote2'
    enabled      BOOLEAN NOT NULL DEFAULT TRUE,    -- se FALSE lo schema viene ignorato
    group_code   TEXT NULL,                        -- es. 'ALL', 'ABB_ONLY', 'ABB2_ONLY'
    run_order    INT  NOT NULL DEFAULT 0,          -- ordine di esecuzione
    creation_ts  TIMESTAMP DEFAULT timezone('utc', CURRENT_TIMESTAMP),
    creator_user VARCHAR  NOT NULL DEFAULT 'ETL_SYSTEM'
);

-- Valori iniziali: schemi FDW esistenti verso ABB e ABB2
INSERT INTO application_staging.etl_source_schema_cfg (schema_name, enabled, group_code, run_order)
VALUES
    ('dwh_remote',  TRUE, 'PROD', 10),
    ('dwh_remote2', TRUE, 'PROD', 20)
ON CONFLICT (schema_name) DO UPDATE
SET enabled   = EXCLUDED.enabled,
    group_code = EXCLUDED.group_code,
    run_order  = EXCLUDED.run_order;

-- Nota:
-- - Per aggiungere una nuova sorgente basta inserire una riga con il nuovo schema FDW.
-- - La procedura application_staging.etl_run_all_lookups può usare questa tabella
--   per determinare automaticamente la lista di schemi da processare.


-- ================================================================
-- PARTE 6b: ETL rejected rows storage (strict mode support)
-- ---------------------------------------------------------------
-- Tabella di dettaglio per tracciare *quali* righe sorgente vengono
-- scartate (non caricate) dalle procedure ETL fact (strict mode),
-- con reason_code e chiavi sorgente in JSONB.
-- ================================================================
CREATE TABLE IF NOT EXISTS application_staging.etl_reject_row (
    reject_id      int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rejected_ts    timestamp NOT NULL DEFAULT timezone('UTC', current_timestamp),
    procedure_name varchar(100) NOT NULL,
    caller         varchar(100) NULL,
    batch_id       varchar(100) NULL,
    foreign_schema text NULL,
    target_date    date NULL,
    plant_id       int8 NULL,
    line_id        int8 NULL,
    process_key    text NULL,
    source_table   text NULL,
    reason_code    text NOT NULL,
    reason_detail  text NULL,
    source_key     jsonb NULL,
    source_payload jsonb NULL
);

CREATE INDEX IF NOT EXISTS etl_reject_row_batch_idx
    ON application_staging.etl_reject_row (procedure_name, batch_id);

CREATE INDEX IF NOT EXISTS etl_reject_row_target_idx
    ON application_staging.etl_reject_row (target_date, plant_id, line_id);

